### ISSUE TITLE
Multiple games need software vertex blending implementation (NOLF2, Divinity 2, Dark Age of Camelot, Warhammer Online, PSU:AOTI)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#100]
https://bugs.winehq.org/show_bug.cgi?id=6955

includes software version patch and henri's instructions for hardware patch

high priority bug if you look how many people this impacts

no recent work involved as far as I know

**Comment by slackner** [comment]
Moved to new bugtracker: https://bugs.wine-staging.com/show_bug.cgi?id=27
