### ISSUE TITLE
       Microsoft Office 2007 diagnosis service crashes on unimplemented function KERNEL32.dll.AllocateUserPhysicalPages

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#108]
https://bugs.winehq.org/show_bug.cgi?id=36527

focht open bug report 

msdn page

http://msdn.microsoft.com/en-us/library/windows/desktop/aa366528%28v=vs.85%29.aspx

**Comment by slackner** [comment]
Moved to https://bugs.wine-staging.com/show_bug.cgi?id=30.
