### ISSUE TITLE
       Zondervan Pradis 6.0 hangs due to ole32.dll.CoGetCurrentLogicalThreadId stub

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#111]
https://bugs.winehq.org/show_bug.cgi?id=17540

This looks really easy to implement

MSDN: http://msdn.microsoft.com/en-us/library/windows/desktop/ms693805%28v=vs.85%29.aspx

Source: http://source.winehq.org/git/wine.git/blob/39562961283ccb7c838c5650b11873e69a8d8e56:/dlls/ole32/ole2stubs.c#l101

--- snip ---
101 HRESULT WINAPI CoGetCurrentLogicalThreadId(GUID *pguid)
102 {
103     FIXME(": stub\n");
104     return E_NOTIMPL;
105 }
--- snip ---

**Comment by slackner** [comment]
Moved to https://bugs.wine-staging.com/show_bug.cgi?id=31.
