### ISSUE TITLE
Change package name to wine-staging on Mageia.

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#118]
Hi,

new users are a bit confused by the fact that wine-staging is partially called wine-compholio. I therefore suggest changing the name everywhere to wine-staging. The repo was already renamed some time ago, but wine-compholio is still used at all the other places. I think it is important to use a common name for the project to be taken serious. In case the suggestion is going to be accepted, the following changes are necessary:

* Rename the wine-compholio packages we provide to wine-staging
We are currently moving to a new build system, so this is the ideal time to test this change without messing around with our normal repositories. The new packages should use `Provides:` or similar mechanism to provide backwards compatibility.

* Replace wine-compholio in README.md and wiki pages

* Alter description of repository on github

* Rename patches/Compholio directory and alter definition file

* Change patch [patches/Compholio/0001-kernel32-Add-winediag-message-to-show-warning-that-t.patch](https://github.com/wine-compholio/wine-staging/blob/master/patches/Compholio/0001-kernel32-Add-winediag-message-to-show-warning-that-t.patch) and [patches/Compholio/0002-winelib-Append-Compholio-at-the-end-of-the-version-s.patch](https://github.com/wine-compholio/wine-staging/blob/master/patches/Compholio/0002-winelib-Append-Compholio-at-the-end-of-the-version-s.patch)

* Find a solution for the IRC channel. Should we use #wine-staging instead and use a forward from #wine-compholio?

We should also think about adding a logo to the github project.

What is your opinion on this change @slackner @compholio?

**Comment by compholio** [comment]
DarkPlayer has updated the Wiki and packages now ;)

**Comment by slackner** [comment]
No, its not fully renamed yet. Other distro builds are still missing, and even for Ubuntu we still need more testing when we do the next release. So reopening for now.

**Comment by DarkPlayer** [comment]
The following packages still use the old name:

- [ ] Fedora
- [ ] Arch Linux
- [ ] Mageia
- [ ] OpenSUSE
- [ ] CentOS

**Comment by DarkPlayer** [comment]
This should also be part of the 1.7.34 Milestone. 

I just removed Fedora and CentOS from the previous list since we currently replace the regular wine version on these systems, no need to rename anything. I am currently working on OpenSUSE, so only Arch Linux is left (which should be easy to solve for @slackner) and Mageia. Mageia is no high priority target so if we run out of time, we may rename later.

**Comment by slackner** [comment]
For most distros the rename was already done with the last release, only Mageia is still missing. It is not really critical because the builds only have very few users. Changing milestone to 1.7.35.

**Comment by titan73** [comment]
1.7.37 is out. is this fixed? shouln't we close it?

**Comment by slackner** [comment]
yes, is already fixed. Closing.
