### ISSUE TITLE
Implement oleaut32.CreateTypeLib

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#12]
RFC for "Implement oleaut32.CreateTypeLib"

|  |  | 
| ------------- | ------------- |
| **Bug**        | https://bugs.winehq.org/show_bug.cgi?id=8780 |
| **Patch**      | https://bugs.winehq.org/attachment.cgi?id=36694 |

This is a little bit hacky since the patch simply forwards the call to CreateTypeLib2 which has a different on-disk fileformat, still this patch fixes many applications.

**Comment by slackner** [comment]
Closing. The current patch is too ugly to merge it, and its rather unlikely that someone of us will work on it in the near future.
