### ISSUE TITLE
Add winscard patches

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#120]
Today I came across the [Scard4Wine](http://sourceforge.net/projects/scard4wine/) project which maintains the winscard implementation written by Mounir IDRASSI. The repository only provides the changed files instead of patches and the original patch sent to wine devel has changed a lot. The files still compile fine, but I can not test them. I converted the line endings from \r\n to \n, changed the tabs to spaces, removed whitespace errors, collapsed empty lines, removed the commented pcsc-lite imports and converted everything into a patch. The result is available at https://dl.dropboxusercontent.com/u/61413222/0001-winscard-Implement-many-functions-based-on-pcsc-lite.patch

My question is whether we are interested in the patch and if someone may be able to test it? There is still a lot space for improvements and it would be good to know whether we should add this patch before cleaning it up.

In case we want to add this patch, I would suggest the following cleanup steps:
* remove the typedefs for the imports and directly use static variables
* instead of checking the imports on every function call, return FALSE during attach if the linux library is unavailable
* find a better way to check if all imports were found
* optional: Do not break the lines on function declaration if it is not necessary (shortens the code length)

Any opinions?

**Comment by slackner** [comment]
Closing. Without a way to test it will be impossible to add those patches.
