### ISSUE TITLE
Provide Managed DirectX replacement assemblies for Mono (Gray Matter demo)

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#147]
support for managed DirectX on Mono would be some kind of metabug but it needs at least one starting bug.

--- snip ---
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DirectX.Direct3D, Version=1.0.2902.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
File name: 'Microsoft.DirectX.Direct3D, Version=1.0.2902.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
  at System.Windows.Forms.Form.OnLoad (System.EventArgs e) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) [0x00000] in <filename unknown>:0 
--- snip ---

Here is the Mono ticked (closed):

https://bugzilla.xamarin.com/show_bug.cgi?id=168

--- quote ---
Please support Managed DirectX on Mono.
That way Mono on Windows or on Wine will be able to run applications that use Microsoft's old Managed DirectX API[1].
I know it's unlikely you'll do this[2], but I figured I might as well try filing a feature request anyway.

[1]. http://en.wikipedia.org/wiki/Managed_DirectX
[2]. http://thread.gmane.org/gmane.comp.gnome.mono.general/38571/focus=38572

Here are some other teams who have wrapped DirectX on .NET:

*  SlimDX -- http://en.wikipedia.org/wiki/SlimDX
*  SharpDX -- http://en.wikipedia.org/wiki/SharpDX
*  MonoGame -- http://monogame.codeplex.com/

Maybe you could reuse some of their work.
--- quote ---

It might be also useful to create a "managed DirectX" winetricks recipe for .NET apps to avoid running DXSETUP.exe which installs the whole bunch of unneeded native dx libs, polluting the WINEPREFIX. 

https://bugs.winehq.org/show_bug.cgi?id=34045

**Comment by slackner** [comment]
The upstream bug report mentions a solution which can be used to workaround this issue:

>Certain DirectX assemblies must be installed/registered, that's why I used the winetricks verb 'directx9' (instead of d3dx9).

and

>If you've installed the full directx9 package via winetricks make sure d3dx9_43.dll set to built-in (only native d3dx9_36 and xact are needed). Indeed, the game crashes when both d3dx9_36 and d3dx9_43 are set to native.

I think it is outside of the scope of Wine-Staging to provide replacment libraries for those Windows DirectX assemblies.

Closing since this issue has very low priority. Upstream Wine also marked this issue with the lowest priority because it doesn't affect many games, and there is an easy workaround.
