### ISSUE TITLE
Multiple games (Guild Wars 2, Risen 2, Tomb Raider 2013): Raw input is broken

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#148]
https://bugs.winehq.org/show_bug.cgi?id=33479

**Comment by Eignar17** [comment]
is it checked patch https://bugs.winehq.org/attachment.cgi?id=49192

**Comment by slackner** [comment]
Fixed with 0121248145472ac8d487c9f848a6543154c28078.

**Comment by Eignar17** [comment]
:3

**Comment by Eignar17** [comment]
@slackner is re open is bug is game Batman Arkham Origins my cursor is on the left and right corners and not move camera not rotates 120 degrees I will send my results to what you see

**Comment by slackner** [comment]
How did you test? Did you compile from source? The bug is fixed in our current Wine-Staging patchset, but not upstream Wine.

**Comment by Eignar17** [comment]
yes is new wine-staging and not fix game Batman Arkham Origins

**Comment by Eignar17** [comment]
is other games is works god

**Comment by slackner** [comment]
That is probably a different bug then, I can't find "Batman" mentioned at all in the upstream bug report. Béla tested with various games and confirmed that it works, see https://bugs.wine-staging.com/show_bug.cgi?id=16#add_comment .

**Comment by Eignar17** [comment]
is test in my pc is send my images and log :+1:

**Comment by Eignar17** [comment]
is problem is batman Arkham Origins is other batman is patch it works is test in other games

**Comment by Eignar17** [comment]
@Slackner is other bug is bug fullscrem
