### ISSUE TITLE
       DVDFlick 1.3.x fails on startup with "automation error" (needs Scripting.Dictionary "get_Item" method implementation)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#153]
https://bugs.winehq.org/show_bug.cgi?id=32476

**Comment by compholio** [comment]
It looks like the issue in this bug is fixed, but some other issue prevents the application from starting.

**Comment by deri82** [comment]
Upstream is fixing this currently. Closing here.
