### ISSUE TITLE
Tom Clancy's Rainbow Six: Lockdown can't save a game (directory not created)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#155]
https://bugs.winehq.org/show_bug.cgi?id=32619

The  debug contains

fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030

which leads here

http://source.winehq.org/git/wine.git/blob/b84e112dd60e9fb6f4d04e82115fcb46e71f9693:/dlls/wbemprox/services.c#l578

 578 static HRESULT WINAPI wbem_services_CreateInstanceEnum(
579 IWbemServices *iface,
580 const BSTR strClass,
581 LONG lFlags,
582 IWbemContext *pCtx,
583 IEnumWbemClassObject **ppEnum )
584 {
585 struct path *path;
586 HRESULT hr;
587
588 TRACE("%p, %s, 0%08x, %p, %p\n", iface, debugstr_w(strClass), lFlags, pCtx, ppEnum);
589
590 if (lFlags) FIXME("unsupported flags 0x%08x\n", lFlags);
591
592 hr = parse_path( strClass, &path );
593 if (hr != S_OK) return hr;
594
595 hr = create_instance_enum( path, ppEnum );
596 free_path( path );
597 return hr;
598 }

create_instance_enum leads

 406 static HRESULT create_instance_enum( const struct path *path, IEnumWbemClassObject **iter )
407 {
408 WCHAR *query;
409 HRESULT hr;
410
411 if (!(query = query_from_path( path ))) return E_OUTOFMEMORY;
412 hr = exec_query( query, iter );
413 heap_free( query );
414 return hr;
415 }

or am i misleading you?

**Comment by slackner** [comment]
I don't think its related to wbemprox. The last test was with 1.7.7, it would be useful to test with more recent wine as a first step, and also with wine staging. We already have included several patches related to directory and file permission handling.

**Comment by deri82** [comment]
It's still valid I opened a new bug report at new bugzilla.
