### ISSUE TITLE
Implement reg.exe query operation

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#16]
RFC for "Implement reg.exe query operation"

|  |  | 
| ------------- | ------------- |
| **Bug**        | https://bugs.winehq.org/show_bug.cgi?id=24017 |
| **Possible Patch 1**      | https://bugs.winehq.org/attachment.cgi?id=45714 |
| **Possible Patch 2**      | https://github.com/cournape/wine/commits/_reg_query/programs/reg/reg.c |
| **Possible Patch 3**      | https://bugs.winehq.org/attachment.cgi?id=30169 |

There are 3 patches from different authors which implement this feature. We need to carefully review the patch we decide to include as the feature is not easy to implement.

**Comment by slackner** [comment]
Moved to https://bugs.wine-staging.com/show_bug.cgi?id=29.
