### ISSUE TITLE
       HTML-Kit Tools trial installer produces an error message in Win7 mode (IShellLink object needs to provide IPropertyStore interface) -focht analyse

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#163]
https://bugs.winehq.org/show_bug.cgi?id=22210

* has small download 
* no patch, but focht analyze

**Comment by compholio** [comment]
Moved to the new bug tracker: https://bugs.wine-staging.com/show_bug.cgi?id=7
