### ISSUE TITLE
Add serial ports to HKLM\\HARDWARE\\DeviceMap\\Serialcomm

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#17]
RFC for "Add serial ports to HKLM\\HARDWARE\\DeviceMap\\Serialcomm"

|  |  | 
| ------------- | ------------- |
| **Bug**        | https://bugs.winehq.org/show_bug.cgi?id=11811 |
| **Patch**      | https://bugs.winehq.org/attachment.cgi?id=17535 |

The patch got rejected according to https://bugs.winehq.org/show_bug.cgi?id=11811#c48 since it does not use HAL for enumerating the serial devices.

**Comment by slackner** [comment]
@compholio: Are you still planning to work on this? For me its not really a high priority bug, so I am also fine with closing it, and focusing more on features required by modern apps/games.

**Comment by slackner** [comment]
The bug doesn't really have very high priority, closing. If someone is planning to work on this again, we can open a new bug report on our new bugtracker.
