### ISSUE TITLE
Error crashes on startup Need for Speed: Most Wanted (2012) 

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#174]
Unhandled exception: page fault on read access to 0x00000050 in 32-bit code (0x00411bfc). 
Register dump: 
CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b 
EIP:00411bfc ESP:0033f754 EBP:0033fe60 EFLAGS:00010246( R- -- I Z- -P- ) 
EAX:01600050 EBX:00000000 ECX:00000000 EDX:00000048 
ESI:0033fa44 EDI:00000000 
Stack dump: 
0x0033f754: 00000000 00000008 00000104 0033fe60 
0x0033f764: 00000000 004128d3 0033f780 01600050 
0x0033f774: 00000104 0033fe60 00000000 00000001 
0x0033f784: 004254d9 0033fa44 00000001 0013ee88 
0x0033f794: 0000000a 00f74710 0033fa44 00000000 
0x0033f7a4: 00000000 00f746cc 00f74704 00ec14ab 
Backtrace: 
=>0 0x00411bfc in nfs13 (+0x11bfc) (0x0033fe60) 
1 0x7b861edc () in kernel32 (0x0033fe78) 
2 0x7b8630bb in kernel32 (+0x530ba) (0x0033feb8) 
3 0x7bc80190 call_thread_func_wrapper+0xb() in ntdll (0x0033fed8) 
4 0x7bc8309d call_thread_func+0x7c() in ntdll (0x0033ffa8) 
5 0x7bc8016e RtlRaiseException+0x21() in ntdll (0x0033ffc8) 
6 0x7bc53efe call_dll_entry_point+0x36d() in ntdll (0x0033ffe8) 
7 0xf759e76d wine_call_on_stack+0x1c() in libwine.so.1 (0x00000000) 
8 0xf759e82b wine_switch_to_stack+0x2a() in libwine.so.1 (0xff952628) 
9 0x7bc59b29 LdrInitializeThunk+0x238() in ntdll (0xff952678) 
10 0x7b869950 __wine_kernel_init+0xbbf() in kernel32 (0xff953598) 
11 0x7bc5aa63 __wine_process_init+0x182() in ntdll (0xff953628) 
12 0xf759c3ba wine_init+0x2b9() in libwine.so.1 (0xff953688) 
13 0x7bf00ebb main+0x7a() in (0xff953ac8) 
14 0xf73bda83 __libc_start_main+0xf2() in libc.so.6 (0x00000000) 
0x00411bfc: movl	0x50(%edi),%eax 
Modules: 
Module	Address	 Debug info	Name (110 modules) 
PE	 340000- 356000	Deferred xinput1_3 
PE	 400000- 11b9000	Export nfs13 
PE	10000000-10207000	Deferred d3dcompiler_43 
ELF	7b800000-7ba5f000	Dwarf kernel32 
\-PE	7b810000-7ba5f000	\ kernel32 
ELF	7bc00000-7bce1000	Dwarf ntdll 
\-PE	7bc10000-7bce1000	\ ntdll 
ELF	7bf00000-7bf03000	Dwarf 
ELF	7d95a000-7d960000	Deferred libxfixes.so.3 
ELF	7d960000-7d96b000	Deferred libxcursor.so.1 
ELF	7d96b000-7d97c000	Deferred libxi.so.6 
ELF	7d97c000-7d980000	Deferred libxcomposite.so.1 
ELF	7d980000-7d98b000	Deferred libxrandr.so.2 
ELF	7d98b000-7d996000	Deferred libxrender.so.1 
ELF	7d996000-7d99c000	Deferred libxxf86vm.so.1 
ELF	7d99c000-7d9a0000	Deferred libxinerama.so.1 
ELF	7d9a0000-7d9a7000	Deferred libxdmcp.so.6 
ELF	7d9a7000-7d9ab000	Deferred libxau.so.6 
ELF	7d9ab000-7d9cd000	Deferred libxcb.so.1 
ELF	7d9cd000-7db01000	Deferred libx11.so.6 
ELF	7db01000-7db14000	Deferred libxext.so.6 
ELF	7db38000-7dbcb000	Deferred winex11 
\-PE	7db40000-7dbcb000	\ winex11 
ELF	7dc2f000-7dc58000	Deferred libexpat.so.1 
ELF	7dc58000-7dc93000	Deferred libfontconfig.so.1 
ELF	7dc93000-7dcbb000	Deferred libpng12.so.0 
ELF	7dcbb000-7dd5b000	Deferred libfreetype.so.6 
ELF	7dd5b000-7dd73000	Deferred libresolv.so.2 
ELF	7dd97000-7ddbc000	Deferred iphlpapi 
\-PE	7dda0000-7ddbc000	\ iphlpapi 
ELF	7ddbc000-7ddd5000	Deferred libz.so.1 
ELF	7ddd5000-7de3c000	Deferred dbghelp 
\-PE	7dde0000-7de3c000	\ dbghelp 
ELF	7de3c000-7df7e000	Deferred oleaut32 
\-PE	7de50000-7df7e000	\ oleaut32 
ELF	7df7e000-7dff8000	Deferred shlwapi 
\-PE	7df90000-7dff8000	\ shlwapi 
ELF	7dff8000-7e22f000	Deferred shell32 
\-PE	7e010000-7e22f000	\ shell32 
ELF	7e22f000-7e259000	Deferred msacm32 
\-PE	7e240000-7e259000	\ msacm32 
ELF	7e259000-7e311000	Deferred winmm 
\-PE	7e260000-7e311000	\ winmm 
ELF	7e311000-7e348000	Deferred ws2_32 
\-PE	7e320000-7e348000	\ ws2_32 
ELF	7e348000-7e3b8000	Deferred setupapi 
\-PE	7e350000-7e3b8000	\ setupapi 
ELF	7e3b8000-7e3cb000	Deferred psapi 
\-PE	7e3c0000-7e3cb000	\ psapi 
ELF	7e3cb000-7e3e6000	Deferred dinput8 
\-PE	7e3d0000-7e3e6000	\ dinput8 
ELF	7e3e6000-7e46b000	Deferred rpcrt4 
\-PE	7e3f0000-7e46b000	\ rpcrt4 
ELF	7e46b000-7e5ad000	Deferred ole32 
\-PE	7e480000-7e5ad000	\ ole32 
ELF	7e5ad000-7e5f5000	Deferred dsound 
\-PE	7e5b0000-7e5f5000	\ dsound 
ELF	7e5f5000-7e6a7000	Deferred msvcrt 
\-PE	7e610000-7e6a7000	\ msvcrt 
ELF	7e6a7000-7e6bb000	Deferred d3d11 
\-PE	7e6b0000-7e6bb000	\ d3d11 
ELF	7e6bb000-7e818000	Deferred user32 
\-PE	7e6d0000-7e818000	\ user32 
ELF	7e818000-7e888000	Deferred advapi32 
\-PE	7e830000-7e888000	\ advapi32 
ELF	7e888000-7e9a7000	Deferred gdi32 
\-PE	7e8a0000-7e9a7000	\ gdi32 
ELF	7e9a7000-7eac2000	Deferred opengl32 
\-PE	7e9c0000-7eac2000	\ opengl32 
ELF	7eac2000-7ec0a000	Deferred wined3d 
\-PE	7ead0000-7ec0a000	\ wined3d 
ELF	7ec0a000-7ec30000	Deferred dxgi 
\-PE	7ec10000-7ec30000	\ dxgi 
ELF	7efa1000-7efae000	Deferred libnss_files.so.2 
ELF	7efae000-7efba000	Deferred libnss_nis.so.2 
ELF	7efba000-7efd3000	Deferred libnsl.so.1 
ELF	7efd3000-7efdc000	Deferred libnss_compat.so.2 
ELF	7efe7000-7f000000	Deferred version 
\-PE	7eff0000-7f000000	\ version 
ELF	f25ae000-f25cb000	Deferred libgcc_s.so.1 
ELF	f4902000-f4926000	Deferred imm32 
\-PE	f4910000-f4926000	\ imm32 
ELF	f4a85000-f6cc9000	Deferred libnvidia-glcore.so.331.38 
ELF	f6cc9000-f6dcd000	Deferred libgl.so.1 
ELF	f6df1000-f6dfa000	Deferred libogg.so.0 
ELF	f6dfa000-f6e26000	Deferred libvorbis.so.0 
ELF	f6e26000-f6f9e000	Deferred libvorbisenc.so.2 
ELF	f6f9e000-f6fd2000	Deferred libflac.so.8 
ELF	f6fd2000-f6fd9000	Deferred libasyncns.so.0 
ELF	f6fd9000-f704b000	Deferred libsndfile.so.1 
ELF	f704b000-f7055000	Deferred libwrap.so.0 
ELF	f7055000-f70a0000	Deferred libdbus-1.so.3 
ELF	f70a0000-f710f000	Deferred libpulsecommon-4.0.so 
ELF	f710f000-f711a000	Deferred libjson-c.so.2 
ELF	f711a000-f7169000	Deferred libpulse.so.0 
ELF	f718f000-f7285000	Deferred libasound.so.2 
ELF	f7294000-f7298000	Deferred libnvidia-tls.so.331.38 
ELF	f72a9000-f72d9000	Deferred winealsa 
\-PE	f72b0000-f72d9000	\ winealsa 
ELF	f72d9000-f72fb000	Deferred mmdevapi 
\-PE	f72e0000-f72fb000	\ mmdevapi 
ELF	f7359000-f739f000	Deferred libm.so.6 
ELF	f739f000-f73a4000	Deferred libdl.so.2 
ELF	f73a4000-f7554000	Dwarf libc.so.6 
ELF	f7554000-f7570000	Deferred libpthread.so.0 
ELF	f7577000-f7580000	Deferred librt.so.1 
ELF	f7582000-f7589000	Deferred libasound_module_pcm_pulse.so 
ELF	f7595000-f774b000	Dwarf libwine.so.1 
ELF	f774d000-f776f000	Deferred ld-linux.so.2 
ELF	f776f000-f7770000	Deferred [vdso].so 
Threads: 
process tid prio (all id:s are in hex) 
00000008 (D) C:\Program Files\EA Games\Need for Speed Most Wanted\NFS13.exe 
0000002a 0 
00000029 0 
00000009 0

**Comment by slackner** [comment]
I assume the game is https://appdb.winehq.org/objectManager.php?sClass=version&iId=8714 ? All users testing with recent versions of wine (>= 1.6.1) have rated platinum, so its unlikely that here is anything to fix. I also tested the demo myself some time ago and it worked fine. For [bug 18477](https://bugs.winehq.org/show_bug.cgi?id=18477) we already have a fix included in recent versions of Wine Staging.

I'll close this bug report, if you still encounter this issue please test  in a fresh wineprefix and provide more information (see my [previous comment](https://github.com/wine-compholio/wine-staging/issues/174#issuecomment-62783640)).

**Comment by Eignar17** [comment]
@slackner is error in new game Need for Speed: Most Wanted (2012) is detect new error in wine-staging 1.7.36 
[02/16/15 12:43:19] - Running wine-wine-compholio1.7.36 NFS13.exe -d3d10 (Working directory : /home/eignar/.PlayOnLinux/wineprefix/nfsmw/drive_c/Program Files/EA Games/Need for Speed Most Wanted)
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:module:load_dll Loader redirect from L"wined3d.dll" to L"wined3d-csmt.dll"
fixme:winediag:wined3d_dll_init Experimental wined3d CSMT feature is currently enabled.
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:dxgi:dxgi_output_GetDesc iface 0x13a150, desc 0x33f3c8 semi-stub!
fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x13a150, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0, mode_count 0x33f3b4, desc (nil) partial stub!
fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x13a150, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0, mode_count 0x33f3b4, desc 0x13e1978 partial stub!
fixme:d3d11:D3D11CreateDevice adapter 0x141e70, driver_type D3D_DRIVER_TYPE_UNKNOWN, swrast (nil), flags 0, feature_levels (nil), levels 0, sdk_version 7, device 0x33f444, feature_level 0x33f44c, contfixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
fixme:thread:SetThreadIdealProcessor (0x74): stub
fixme:thread:SetThreadIdealProcessor (0x88): stub
fixme:thread:SetThreadIdealProcessor (0x8c): stub
fixme:thread:SetThreadIdealProcessor (0x98): stub
[02/16/15 21:24:53] - Running wine-wine-compholio1.7.36 regedit (Working directory : /usr/share/playonlinux/python)
[02/16/15 21:24:53] - User modified something in the registry manually
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
[02/18/15 13:31:34] - Running wine-wine-compholio1.7.36 NFS13.exe -d3d10 (Working directory : /home/eignar/.PlayOnLinux/wineprefix/nfsmw/drive_c/Program Files/EA Games/Need for Speed Most Wanted)
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:module:load_dll Loader redirect from L"wined3d.dll" to L"wined3d-csmt.dll"
fixme:winediag:wined3d_dll_init Experimental wined3d CSMT feature is currently enabled.
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:dxgi:dxgi_output_GetDesc iface 0x142250, desc 0x33f3c8 semi-stub!
fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x142250, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0, mode_count 0x33f3b4, desc (nil) partial stub!
fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x142250, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0, mode_count 0x33f3b4, desc 0x13e1978 partial stub!
fixme:d3d11:D3D11CreateDevice adapter 0x142230, driver_type D3D_DRIVER_TYPE_UNKNOWN, swrast (nil), flags 0, feature_levels (nil), levels 0, sdk_version 7, device 0x33f444, feature_level 0x33f44c, contfixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
fixme:thread:SetThreadIdealProcessor (0x74): stub
fixme:thread:SetThreadIdealProcessor (0x88): stub
fixme:thread:SetThreadIdealProcessor (0x94): stub
fixme:thread:SetThreadIdealProcessor (0x98): stub

is report in https://bugs.wine-staging.com a new error?

**Comment by Eignar17** [comment]
![captura de pantalla de 2015-02-18 13_31_43](https://cloud.githubusercontent.com/assets/8561550/6255103/91b1d370-b77b-11e4-8aa0-8cb4cca9c5f5.png)
is bug my sistem ubuntu 14.04 64bits is video nvidia geforce 210

**Comment by slackner** [comment]
DirectX 10 is not supported by Wine, why are you starting NFSMW with `-d3d10` as commandline argument? That can't work.

Yes, https://bugs.wine-staging.com/ is the new bugtracker, but old issues (reported before the new bug tracker was created) can also stay here on github.

**Comment by Eignar17** [comment]
yes its not works -d3d10
