### ISSUE TITLE
"North American Birds" fails to launch (Unimplemented function ole2disp.dll.VARIANTCHANGETYPE)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#176]
contains austin made stub patch which seems wrong to me

https://bugs.winehq.org/show_bug.cgi?id=14449

http://msdn.microsoft.com/en-us/library/windows/desktop/ms221258%28v=vs.85%29.aspx

**Comment by compholio** [comment]
This should be fixed in upstream Wine 1.7.32, can you confirm?

**Comment by deri82** [comment]
Havent tried but I quess this could be closed.

**Comment by deri82** [comment]
Assuming fixed upstream. Cant test.
