### ISSUE TITLE
Various Microsoft component/prerequisite installers hang due to bug in property sheet control (WIC, PowerShell, XPSEPSC) *patch*

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#181]
focht analyze, patch

the patch is said to be working, no idea why it isnt merged

https://bugs.winehq.org/show_bug.cgi?id=16876

**Comment by compholio** [comment]
Moved to the new bug tracker: https://bugs.wine-staging.com/show_bug.cgi?id=6
