### ISSUE TITLE
Multiple Microsoft product installers fail due missing shell app path expansion (Visual Studio .NET 2002, 2003, Visual Foxpro 9.0)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#191]
includes focht analyze
includes patch

https://bugs.winehq.org/show_bug.cgi?id=8439

7 year old bug

**Comment by compholio** [comment]
Moved to the new bug tracker: https://bugs.wine-staging.com/show_bug.cgi?id=5
