### ISSUE TITLE
vSphere 5.5 fails to load Mono (libmono-2.0-x86.dll not linked statically)

### ISSUE THREAD

**Issue by NTMan** [wine-compholio/wine-staging#194]
$ wine --version
wine-1.7.30 (Compholio)

$ ./VpxClient.exe
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"configSections" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"section" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"system.net" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"connectionManagement" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"clear" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"appSettings" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"cmdlineFallback" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"generatePublisherEvidence" in state 4
err:module:import_dll Library libgcc_s_sjlj-1.dll (which is needed by L"C:\\windows\\mono\\mono-2.0\\bin\\libmono-2.0-x86.dll") not found
err:mscoree:load_mono Could not load Mono into this process

https://gist.github.com/NTMan/03b46675ca5ad63cc91d

**Comment by NTMan** [comment]
Hi I am updated to Fedora 22, and error message now changed:

$ ./.wine/drive_c/Program\ Files/VMware/Infrastructure/Virtual\ Infrastructure\ Client/Launcher/VpxClient.exe 
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"configSections" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"section" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"system.net" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"connectionManagement" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"clear" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"appSettings" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 6
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"cmdlineFallback" in state 2
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"generatePublisherEvidence" in state 4
err:module:import_dll Library libwinpthread-1.dll (which is needed by L"C:\\windows\\mono\\mono-2.0\\bin\\libmono-2.0-x86.dll") not found
err:mscoree:load_mono Could not load Mono into this process

$ wine --version
wine-1.7.40 (Staging)

**Comment by slackner** [comment]
I assume you are the same person as in https://bugs.wine-staging.com/show_bug.cgi?id=230, right? Closing this one to avoid having multiple reports about the same issue.
