### ISSUE TITLE
Add Realtime priority patches

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#202]
https://dl.dropboxusercontent.com/u/879835/wine-rt-101107.patch

**Comment by deri82** [comment]
Is this still valid with recent additions? "Support for linux priority levels for faster performance"

**Comment by slackner** [comment]
Yep, can be closed, added in https://github.com/wine-compholio/wine-staging/commit/3b9b44454b081feceae23c36fc1b6e31b10788e9. Thanks
