### ISSUE TITLE
WinLaunch 0.4.6.1 (OSX Style free Launcher) complains about missing "%USERPROFILE%\\Application Data\\Microsoft\\Windows\\Themes\\" directory

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#207]
https://bugs.winehq.org/show_bug.cgi?id=34910

focht analyze

**Comment by deri82** [comment]
I think this is shell(32) issue. They create user related folders there.

**Comment by slackner** [comment]
Fixed in https://github.com/wine-compholio/wine-staging/commit/c17d191886b1c2cd42ae0012cf8b2d32a2d3e1c6.
