### ISSUE TITLE
HyperCam 2.x crashes on startup

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#209]
focht analyse

https://bugs.winehq.org/show_bug.cgi?id=27595

**Comment by deri82** [comment]
For what is it worth Bruno added small patch. This bug might be fixed upstream soon.

**Comment by compholio** [comment]
It looks like Bruno hasn't submitted this yet, so I'm adding the patch link:
https://bugs.winehq.org/attachment.cgi?id=50355

**Comment by slackner** [comment]
Added in 673cb4f8479a3e6939b195385780a7ad0de3cad7.
