### ISSUE TITLE
SUPERLEX.EXE (Oxford dictionary) NOT run.

### ISSUE THREAD

**Issue by geobarrod** [wine-compholio/wine-staging#214]
https://bugs.winehq.org/show_bug.cgi?id=37675

**Comment by DarkPlayer** [comment]
Wine Staging 1.7.34 was released yesterday containing the fix mentioned by @slackner. As soon as the update is available for you, you should test if the problem is gone now.

**Comment by slackner** [comment]
Assuming it is fixed.

**Comment by geobarrod** [comment]
Yes, fixed, thanks very much.
