### ISSUE TITLE
Stronghold Kingdoms: loops after update *contains short fixing patch*

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#216]
https://bugs.winehq.org/show_bug.cgi?id=23934

**Comment by compholio** [comment]
Has anyone taken a look at this patch?

**Comment by slackner** [comment]
I didn't take a look yet, but changes in shell32 are always a bit difficult - the code partially has such a bad quality that almost every change breaks new stuff. xD Not sure if its possible to write a test for that, but if yes it would be definitely useful. At least needs some manual testing.

**Comment by compholio** [comment]
Well, I'll go ahead and declare that I'll check this out then.  Can't promise I'll get to it quickly though ;)

**Comment by compholio** [comment]
lol, clearly not right yet:
shlexec: 1342 tests executed (151 marked as todo, 105 failures), 0 skipped

**Comment by compholio** [comment]
This issue is fixed by commit a5ec351f6eb76093c1f8fd894d5aa9a371a4d2b9.
