### ISSUE TITLE
drawStridedSlow can be more efficient

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#219]
is intro project god efficient 
bug 
https://bugs.winehq.org/show_bug.cgi?id=32096

**Comment by slackner** [comment]
The "hack" written in [comment 3](https://bugs.winehq.org/show_bug.cgi?id=32096#c3) is clearly no suitable solution. It was just to demonstrate what could be changed theoretically. The bug reporter [announced](https://bugs.winehq.org/show_bug.cgi?id=32096#c7) that he would submit a better patch to wine-patches, but I guess he never did that. I was unable to find any submission which would match this bug description.

Based on the comments the issue only affected specific graphic card, which were already very old when the bug reporter initially opened this issue about 3 years ago. It is very unlikely that people still use it nowadays, and we also have no correct patch or at least a way to test. It doesn't make sense to work on this issue, so I'll close this bug report.

**Comment by Eignar17** [comment]
@slackner  is it create new patch optimize graphics ?

**Comment by slackner** [comment]
@Eignar17: I am really having a bit trouble to understand what you mean. I think I've explained everything in my [previous comment](https://github.com/wine-compholio/wine-staging/issues/219#issuecomment-71789041), what was unclear about that? The patch will not help at all unless you have such an ancient graphic card. It doesn't make sense to write new patches to fix such a bug, where probably not even a single user is affected anymore.

**Comment by Eignar17** [comment]
ok i understand you
