### ISSUE TITLE
Tom Clancy's Rainbow Six: Vegas 2 fails to launch (number of quality levels for D3DMULTISAMPLE_NONMASKABLE multiple-sample type must not exceed 8)

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#220]
is bug
https://bugs.winehq.org/show_bug.cgi?id=12652
and patch
https://bugs.winehq.org/attachment.cgi?id=47596
@DarkPlayer  @slackner  @compholio add patch?

**Comment by deri82** [comment]
Austin has suggested a new patch.

**Comment by slackner** [comment]
Patch was added in https://github.com/wine-compholio/wine-staging/commit/cd62b5bedccb010717a666205c19f4dc068fa879.
