### ISSUE TITLE
Spellforce has bad quality ground textures

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#228]
is bug 

https://bugs.winehq.org/show_bug.cgi?id=14522#c30

and patch

https://bugs.winehq.org/attachment.cgi?id=49876

is patch shows good results in texture but check if useful  @DarkPlayer  @slackner  @compholio  add patch?

**Comment by titan73** [comment]
A patch has been commited upstream that should help the situation https://bugs.winehq.org/show_bug.cgi?id=14522#c36.

**Comment by Eignar17** [comment]
ok :+1:
