### ISSUE TITLE
 Error 1608 with Rome Total War installer

### ISSUE THREAD

**Issue by stfacc** [wine-compholio/wine-staging#234]
Running the installer of Rome Total War I have:

1608: unable to create install driver instance
Error code: -2147221164

wine 1.7.30 on Fedora 21

$ wine --check-libs
libcapi20.so.3: missing
libcups.so.2: missing
libdbus-1.so.3: /lib/libdbus-1.so.3
libfontconfig.so.1: /lib/libfontconfig.so.1
libfreetype.so.6: /lib/libfreetype.so.6
libGL.so.1: /lib/libGL.so.1
libgnutls.so.28: /lib/libgnutls.so.28
libgsm.so.1: /lib/libgsm.so.1
libjpeg.so.62: /lib/libjpeg.so.62
libncurses.so.5: /lib/libncurses.so.5
libnetapi.so: missing
libodbc.so.2: missing
libOSMesa.so.8: missing
libpcap.so.1: missing
libpng16.so.16: /lib/libpng16.so.16
libsane.so.1: missing
libtiff.so.5: /lib/libtiff.so.5
libv4l1.so.0: /lib/libv4l1.so.0
libX11.so.6: /lib/libX11.so.6
libXcomposite.so.1: missing
libXcursor.so.1: /lib/libXcursor.so.1
libXext.so.6: /lib/libXext.so.6
libXi.so.6: /lib/libXi.so.6
libXinerama.so.1: /lib/libXinerama.so.1
libXrandr.so.2: /lib/libXrandr.so.2
libXrender.so.1: /lib/libXrender.so.1
libxslt.so.1: /lib/libxslt.so.1
libXxf86vm.so.1: /lib/libXxf86vm.so.1

**Comment by deri82** [comment]
Are we waiting for a new Christmas here before feedback ?

**Comment by slackner** [comment]
@deri82: There is no need to be unfriendly.

Since there wasn't any activity since some time I assume that this question is abandoned. If the problem still exists, please open a new question/discussion on our new bugtracker.
