### ISSUE TITLE
Tera Online has Difficulty Starting

### ISSUE THREAD

**Issue by eliwap** [wine-compholio/wine-staging#238]
Hi

I previously posted this at https://bugs.winehq.org/show_bug.cgi?id=37688 before realizing that I needed to post here because I am using Fedora; currently version 21

After a recent update to the Launcher of the game Tera Online I started to receive an error that:

The TERA Launcher is unable to load the
SteamSupport.dll

ErrorMessage: Interop load failed

A screen shot is included.

![tera_launcher_steamsupport_error](https://cloud.githubusercontent.com/assets/10329392/5563865/60efeeb4-8ea1-11e4-93de-80aad421b332.jpg)

**Comment by eliwap** [comment]
Brilliant.. This works... I will try to get the patch mentioned in:
https://bugs.winehq.org/show_bug.cgi?id=37338
And report here. I understand from reading the posts that the patch still requires some work.

**Comment by Kazunekit** [comment]
No, the patch mentioned in https://bugs.winehq.org/show_bug.cgi?id=37338 is already in wine-staging: https://github.com/wine-compholio/wine-staging/tree/master/patches/ntdll-NtQuerySection

**Comment by eliwap** [comment]
Bugger.... That means the problem still exists despite the fact doesn't it?

**Comment by Kazunekit** [comment]
I'm guessing it might be either:
1) Tera Launcher doesn't cleanly shutdown. On my system, it takes around 10minutes to completely shutdown, after I press the X.
2) Something else needs to clean up those message_queue_* files. Possibly wineserver needs to remove those files once the application is down or something like that.

It's hard to say why the files are left even after the application is shut down. Possibly looking through logs might give some information, in case there's another stub that is responsible for cleaning.

**Comment by eliwap** [comment]
Me too. And it usually closes with some kind of error message

**Comment by eliwap** [comment]
Here is the error.
![tera_crash_when_closing](https://cloud.githubusercontent.com/assets/10329392/5592201/4f86af36-91c7-11e4-974f-944a48bdaa89.jpg)

**Comment by Kazunekit** [comment]
Yeah, same. Gonna look into debugging it and opening an issue on Wine if needed, since I'm not using staging.

**Comment by eliwap** [comment]
Thank you. You are so much better at this than me :)

**Comment by eliwap** [comment]
The steamsupport.dll error seems to be resolved with wine-stagging 1.7.34 :).

**Comment by eliwap** [comment]
wrote too soon :( The problem persists

**Comment by titan73** [comment]
I understand there is to problems:
1) NtQureySection fixed in wine-staging by https://github.com/wine-compholio/wine-staging/tree/master/patches/ntdll-NtQuerySection
2) Missing FileRenameInformation (information class 10) missing from NtSetInformationFile
    (this is just file renaming)

The 2nd problem does not seem hard to fix? Does someone sees any difficulty? If not that would be good to nominate it for 1.7.35.

**Comment by titan73** [comment]
This is Linux only but that might help:
http://stackoverflow.com/questions/13861400/rename-from-a-file-descriptor

**Comment by eliwap** [comment]
Problem persists with 1.7.36 wine-staging

**Comment by deri82** [comment]
This might be fixed in next wine-staging release, since 

"2) Missing FileRenameInformation (information class 10) missing from NtSetInformationFile
(this is just file renaming)"

is marked on the bug fixes list.

**Comment by deri82** [comment]
@eliwap  Could you try this bug when you have a new wine-staging 1.7.45?

**Comment by DarkPlayer** [comment]
This bug should be fixed, Tera Online is on my list of applications / games I test before we push a new release.

**Comment by eliwap** [comment]
Just installed it. I will be testing it tonight after I get home from work. I will let you know. And thanks :)

**Comment by eliwap** [comment]
Yay!!! After a couple of days and logging in and out, I am very happy to report that I had no trouble starting the game when it relates to this issue :)

Thank you

**Comment by deri82** [comment]
How about this then? https://github.com/wine-compholio/wine-staging/issues/240

**Comment by titan73** [comment]
The bug is fixed. This ticket can be closed then.
