### ISSUE TITLE
Fix issues with ISOLATIONAWARE_MANIFEST_RESOURCE_ID / activation contexts

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#24]
RFC for "Enumerate through all directory entries of a resource"

|  |  | 
| ------------- | ------------- |
| **Bug**        | https://bugs.winehq.org/show_bug.cgi?id=18889 |
| **Patch**      | https://bugs.winehq.org/attachment.cgi?id=47180 |

**Comment by slackner** [comment]
Closing. The current patch is only a hack.
