### ISSUE TITLE
Implement D3DXComputeNormals and add stub for D3DXComputeNormalMap

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#242]
These patches fixe bug https://bugs.winehq.org/show_bug.cgi?id=26379:
- http://ix.io/fxI
- http://ix.io/fxJ

HDR demo needs only first patch to run. No object is displayed. I will investigate.
Venice demo needs  both patch to run. The water is not well correctly rendered as it needs D3DXComputeNormalMap to be really implemented. I have patch working here but it's not finished.

I don't have tested other demos as there are no link provided.

Btw @slackner, can you add that changes http://ix.io/fxK to those stubs? thx

**Comment by titan73** [comment]
Oups use http://ix.io/fxL for the first patch instead.

**Comment by titan73** [comment]
For D3DComputeNormalMap, does someone knows what is exactly D3DX_CHANNEL_LUMINANCE? All other defines are straightforward but this one is not clear at all. Where should I take the height in source pixel.

**Comment by slackner** [comment]
Added in 40e8ab0c082b458f9596d988e53345398f6c0764.

The changes to the stubs were not necessary, I already fixed that when adding your patches to wine-staging.

**Comment by slackner** [comment]
Forgot to mention that I also don't know what D3DX_CHANNEL_LUMINANCE is for :/

**Comment by titan73** [comment]
Ah ok thx.
D3DX_CHANNEL_LUMINANCE => Indicates the luminances of the red, green, and blue channels should be used. But that does not help.

**Comment by titan73** [comment]
I'll wrtie some tests for that.
