### ISSUE TITLE
[EA Origin]Unable to download game since the new version

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#244]
Related to upstream bug https://bugs.winehq.org/show_bug.cgi?id=31438
Fix https://bugs.winehq.org/attachment.cgi?id=50384&action=diff
Associated tests https://bugs.winehq.org/attachment.cgi?id=50410&action=diff
Successhully tested with EA Origin

**Comment by slackner** [comment]
Should definitely be merged till 1.7.34. Leaving this task to @compholio since he already self-assigned it. ;)

**Comment by compholio** [comment]
Fixed by commit 3f85f1763b0f46a70b3e6465cbe09dc277df6653.
