### ISSUE TITLE
New patch system needs beta-testing!

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#246]
I have just pushed the updated patch system. For those that haven't followed our discussions on IRC and in earlier bug reports, a rewrite was definitely needed because of the terrible speed of our old Makefile based solution. I am not talking about the speed to run the Makefile, but the computations which are necessary for the script to create it, and to ensure that it will always apply fine on the Wine source tree.

Please test the new script. I am also planning to add a couple of new features including stacked git support soon.

Usage examples:
```
# From inside of the wine tree
/path/to/wine-compholio/patches/patchinstall.sh --backend=git --all

# From outside of the wine tree
patchinstall.sh DESTDIR=/path/to/wine/tree --backend=git --all

# Apply directly, without using git
patchinstall.sh --all

# Apply only a specific patch (please note that .ok is no longer needed)
patchinstall.sh fonts-Missing_Fonts

# Exclude a specific patch
patchinstall.sh --all -W fonts-Missing_Fonts

# Ecluding a patchset which breaks a dependency, the user will be informed
patchinstall.sh --all -W wined3d-CSMT_Helper

# Do not autoupdate configure / tools and do not apply the patchlist
patchinstall.sh --no-autoupdate fonts-Missing_Fonts

...
```

I am also interested in any improvements to make the script compatible with alternative shells.

**Comment by titan73** [comment]
When do you thinkstacked git support will be ready?

**Comment by titan73** [comment]
Btw, in last example, what does "do not apply the patchlist" mean?

**Comment by slackner** [comment]
@titan73: I think it will be implemented within the next few hours or worst-case until tomorrow, there is not really much missing, and the new script based method to apply patches simplifies everything a lot.

"do not apply the patchlist" -> In order to implement `wine --patches` there is one last autogenerated patch, which contains a string array based on which patches were applied. This was added a while ago because some distros did not apply all the patches, and it was a mess to figure out afterwards what is going wrong, when it is just a broken build.

Nevertheless, this last autogenerated patch only makes sense when applying the patches for a build, not when working on them. `--backend=stg` will implicitly turn off this last patch, because it never has to be modified manually.

**Comment by titan73** [comment]
I did some testing. Here are some results and comments:

Duration of all patchsets applying:
- patch => 7s
- git => 54s
- git-am => 54s
- stg => 3m27s

Here are some warnings generated by some patches:
Applying server-Unexpected_Wakeup/0001-server-Avoid-sending-unexpected-wakeup-with-uninitia.patch
warning: server/thread.c est de type 100755, mais 100644 attendu
Applying server-CreateProcess_ACLs/0001-server-Support-for-thread-and-process-security-descr.patch
warning: server/protocol.def est de type 100755, mais 100644 attendu
Applying server-Unexpected_Wakeup/0001-server-Avoid-sending-unexpected-wakeup-with-uninitia.patch
warning: server/thread.c est de type 100755, mais 100644 attendu
Applying ws2_32-Connect_Time/0001-ws2_32-Implement-returning-the-proper-time-with-SO_C.patch
warning: server/protocol.def est de type 100755, mais 100644 attendu
Applying ws2_32-TransmitFile/0005-ws2_32-Add-support-for-TF_DISCONNECT-and-TF_REUSE_SO.patch
warning: server/protocol.def est de type 100755, mais 100644 attendu
Application : ntdll: Move code to update user shared data into a separate function.
warning: dlls/ntdll/thread.c est de type 100755, mais 100644 attendu
Application : winepulse: Add IAudioRenderClient and IAudioCaptureClient
/home/titan/wine/wine-staging/git/.git/rebase-apply/patch:319: trailing whitespace.
Application : winepulse: Add IAudioClock and IAudioClock2
/home/titan/wine/wine-staging/git/.git/rebase-apply/patch:117: trailing whitespace.
Application : winepulse: fixup IsFormatSupported calls
/home/titan/wine/wine-staging/git/.git/rebase-apply/patch:372: trailing whitespace.

DESTDIR with relative patch does not work:
patches/patches/patchinstall.sh DESTDIR=git --backend=git wined3d-CSMT_Helper
Applying wined3d-DXTn/0001-wined3d-Add-support-for-DXTn-software-decoding-throu.patch
patches/patches/patchinstall.sh: ligne 677 : cd: git: file or directory does not exist
ERROR: Failed to apply patch, aborting!
It seems DESTDIR should be relative to patches subdir

Stacked git patch names are truncated:
Applying wined3d-DXTn/0001-wined3d-Add-support-for-DXTn-software-decoding-throu.patch
Checking for changes in the working directory ... done
Importing patch "staging-wined3d-dxtn-0001" ... done
Now at patch "staging-wined3d-dxtn-0001"
Applying wined3d-DXTn/0002-wined3d-Improve-DXTn-support-and-export-conversion-f.patch
Checking for changes in the working directory ... done
Importing patch "staging-wined3d-dxtn-0002" ... done
Now at patch "staging-wined3d-dxtn-0002"
Applying wined3d-DXTn/0003-wined3d-add-DXT1-to-B4G4R4A4-DXT1-to-B5G5R5A1-and-DX.patch
Checking for changes in the working directory ... done
Importing patch "staging-wined3d-dxtn-0003" ... done
Now at patch "staging-wined3d-dxtn-0003"
Applying makedep-PARENTSPEC/0001-makedep-Add-support-for-PARENTSPEC-Makefile-variable.patch
Checking for changes in the working directory ... done
Importing patch "staging-makedep-parentspec" ... done
Now at patch "staging-makedep-parentspec"
Applying wined3d-CSMT_Helper/0001-wined3d-Merge-get_pitch-functions.patch
Checking for changes in the working directory ... done
Importing patch "staging-wined3d-csmt_helper" ... done
Now at patch "staging-wined3d-csmt_helper"
Applying wined3d-CSMT_Helper/0002-wined3d-Add-second-dll-with-STAGING_CSMT-definition-.patch
Checking for changes in the working directory ... done
Importing patch "staging-wined3d-csmt_helper-0" ... done
Now at patch "staging-wined3d-csmt_helper-0"

**Comment by titan73** [comment]
Importing all patches with 'stg import -s' => 1m55
There is improvement but it is not fantastic.

**Comment by slackner** [comment]
@titan73: Thanks for testing.

@DarkPlayer: @compholio: @titan73: Please try out this patch http://ix.io/fGP, and check if it still works. It switches from bash to /bin/sh. This might be useful for distros which do not install bash by default.

**Comment by titan73** [comment]
New patch tested successfuly with 4 backends.

**Comment by slackner** [comment]
Also works fine on the Ubuntu build servers:
https://launchpadlibrarian.net/194488570/buildlog_ubuntu-trusty-i386.wine-staging_1.7.34~daily-201501101513~ubuntu14.04.1_UPLOADING.txt.gz

Closing as fixed. The remaining issues (fix apply warnings, support for relative paths, and optimizations for stacked git) can be fixed after the release.
