### ISSUE TITLE
Windows Live Essentials 2012 web installer crashes (CreateHardLinkTransactedW and DeleteFileTransactedW missing)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#247]
This is upstream bug

https://bugs.winehq.org/show_bug.cgi?id=32229

contains 2 stub patches which werent merged into upstream.

http://msdn.microsoft.com/en-us/library/windows/desktop/aa363916%28v=vs.85%29.aspx
http://msdn.microsoft.com/en-us/library/windows/desktop/aa363861%28v=vs.85%29.aspx

**Comment by slackner** [comment]
I looked at this issue already, and was not sure if it is a good idea to merge them.

"Transacted" means that the operations are not directly performed, but instead they are saved in a queue, until the transaction is later committed. With the stubs in place Wine would execute the operation too early. The worst part is that transactions can also be aborted, but when Wine already deleted the file its impossible to undo that...
