### ISSUE TITLE
wined3d: Use proper color key type define when calling  wined3d_texture_set_color_key

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#250]
The patch is at http://ix.io/fEB.
It fixes bug https://bugs.winehq.org/show_bug.cgi?id=37748 which was a regression caused by commit a8ab56941577a01e17b947cddd374ba52ffd8245.
This was obviously a mistake done when simplifying some code.

**Comment by slackner** [comment]
Added in cb475f78f9fa4ea2dc70294e0721ce9a5145404e. Good job! :)
