### ISSUE TITLE
Do not attempt to use DXTn conversion functions when library failed to load

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#253]
This is something where I am not completely happy about since we initially added DXTn support. If the lib is not present the conversion function is still available, and will basically return a texture with uninitialized memory... Marking as milestone for 1.7.34.

**Comment by slackner** [comment]
Should be fixed with 87fd17de51f75e73919d468a31ff16fa209f35e9.

Needs a bit testing to ensure we didn't break anything, and also compile test with DXTn disabled.

**Comment by titan73** [comment]
Tested successfully:
- dxt disable (in configure)
- dxt enable + libtxc_dxtc missing
- dxt enable + libtxc_dxtc present

**Comment by slackner** [comment]
Just did some testing myself, and everything confirmed to work fine. Closing.
