### ISSUE TITLE
Add wrapper for nvenc.dll (CUDA video encoder).

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#254]
Split off from https://github.com/wine-compholio/wine-staging/issues/231. Doesn't make sense to implement it right now because the linux equivalent library is only included in Nvidia beta drivers. We will have to wait a couple of weeks/months until the feature is included in stable drivers, and then can continue working on this.

**Comment by oscarbg** [comment]
Hi,
some updates on this.. since yesterday current non beta linux driver (346.35) supports it..
second please check implementation of wrapper works with new nvencode sdk 5.0 samples which add support for Maxwell HEVC HW encoder.. (I can check that also..)

**Comment by DarkPlayer** [comment]
I wrote most of the cuda/nvapi code, but the nvenc stuff needs to be written by someone else or you will need to wait some time. My Geforce GTX 260 is no longer supported by this driver, so I can not implement this at the moment.

**Comment by slackner** [comment]
I was planning to take a look at this, as soon as Archlinux packages are available (which shouldn't take that long). I'll assign it to me, but I fear that it will not be possible till 1.7.35, we have a lot of other tasks marked as milestone. ;)

**Comment by titan73** [comment]
nvenc is in 1.7.36. shouldn't we close this bug?

**Comment by DarkPlayer** [comment]
The correct name of the dll is actually nvencodeapi.dll / nvencodeapi64.dll and was added in 1.7.36 as @titan73 said, so we can close the bug report as fixed.
