### ISSUE TITLE
Improve winedbg

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#255]
Winedbg is quite limited compared to gdb and I therefore would like to suggest some improvements.

- [ ] Add tracepoints
A tracepoint is similar to a breakpoint with the difference that the debugger only prints the executed address / command and then directly continues without waiting for input. GDB also supports executing scripts when a tracepoint is triggered and you can save data for later analysis. This is most probably a bit too complicated, but adding simply tracepoints to check when a function gets executed is already useful.

- [ ] Add trace-all command
This command should single step through the program and print every executed assembler instruction until an exception / breakpoint occurs. It would be useful to print all registers affected by this instruction  but this may be a bit hard to implement.

Feel free to extend this list, if you have further ideas.

**Comment by deri82** [comment]
I dont know how easy or hard it's to implement but upstream has bug report open that it doesnt support sse2 calls.

**Comment by deri82** [comment]
winedbg does not support fixed host:port parameter requested upsttream
https://bugs.winehq.org/show_bug.cgi?id=21404

**Comment by slackner** [comment]
Closing for now. A new bug report can be opend on our new bugtracker, as soon as someone is actively working on it.
