### ISSUE TITLE
IDirectSoundBufferImpl_SetFX needed for sound effects in several games

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#259]
Is bug https://bugs.winehq.org/show_bug.cgi?id=10603 in wine directx sound fix error and variable games

**Comment by titan73** [comment]
According to comment 15 (https://bugs.winehq.org/show_bug.cgi?id=10603#c15), the problem, at least for 3 games, is in OpenFile and not IDirectSoundBufferImpl_SetFX.

**Comment by titan73** [comment]
Regarding IDirectSoundBufferImpl_SetFX, only Prince of Persia SoT seems affected (https://bugs.winehq.org/show_bug.cgi?id=10603#c7). There is a confusion between sound effect (explostion, noise, ...) and effect processing (echo, flanger, ...). People mostly complain about missing sounds.
