### ISSUE TITLE
Impossible to apply job object patch with staging patchset

### ISSUE THREAD

**Issue by rinaldus** [wine-compholio/wine-staging#260]
I can apply jobs objects patch ( described here: https://bugs.winehq.org/show_bug.cgi?id=33723 ) to vanilla wine. But it gives errors with your patchset: http://pastebin.com/WNhrDwB2
Please, can you help me to fix this conflict? I need both job objects patch and your patchset!

**Comment by titan73** [comment]
Only 1 hunk failed. Just use 'patch -p1 foo.patch ' and post the .rej file.

**Comment by slackner** [comment]
Yeah, its really a mess how epatch tries to bruteforce the -p level, but thats not your fault. ;)

Here is a rebased version, I didn't check if it compiles though: http://ix.io/fGT
It has to be applied after the rest of the wine-staging patches.

Please note that this is related to #40, we were also planning to add that patchset to wine-staging itself, but didn't have time to do that yet. It probably also needs some improvements, and unfortunately the original author isn't working on it anymore.

**Comment by rinaldus** [comment]
It works! Thank you very much! I will be very glad if you add this patch to your patchset when you have time.

**Comment by slackner** [comment]
@rinaldus: Glad to hear that it works :) We will hopefully have some time to take a closer look at this patchset until 1.7.35, I agree that it would be really nice to have it included as fast as possible.

You can check https://github.com/wine-compholio/wine-staging/issues/40 for the current status.

Regards,
Sebastian
