### ISSUE TITLE
Add purist mode

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#261]
Many dlls return FALSE when DllMain with DLL_WINE_PREATTACH is called so the native version of the dll is used instead if it exists.

Currenly the only method to use purist mode is to do 'winetricks alldlls=builtin'. The problems are:
- all previous overrides are lost
- all the registry is polluted with a lot of overrides
- it's hard to see what's native among all those builtin overrides

I could use 'winetricks alldlls=builtin' and use WINEDLLOVERRIDES but sometimes it's not convenient and I would prefer to edit them in winecfg. I did some requests about that to winetricks author but it was not updated.

For these reasons I have always patch below in my stack. So my proposal is to have something similar that can be enable/disabled via the registry and have a purist mode in the dll overrides section of winecfg.

What do you think?

```
diff --git a/dlls/ntdll/loader.c b/dlls/ntdll/loader.c
index e1444d2..6b7c97a 100644
--- a/dlls/ntdll/loader.c
+++ b/dlls/ntdll/loader.c
@@ -2114,9 +2114,9 @@ static NTSTATUS load_dll( LPCWSTR load_path, LPCWSTR libname, DWORD flags, WINE_
             (MODULE_InitDLL( *pwm, DLL_WINE_PREATTACH, NULL ) != STATUS_SUCCESS))
         {
             /* stub-only dll, try native */
-            TRACE( "%s pre-attach returned FALSE, preferring native\n", debugstr_w(filename) );
-            LdrUnloadDll( (*pwm)->ldr.BaseAddress );
-            nts = STATUS_DLL_NOT_FOUND;
+            FIXME( "%s pre-attach returned FALSE, preferring native\n", debugstr_w(filename) );
+            //LdrUnloadDll( (*pwm)->ldr.BaseAddress );
+            //nts = STATUS_DLL_NOT_FOUND;
         }
         if (nts == STATUS_DLL_NOT_FOUND && loadorder != LO_BUILTIN)
             nts = load_native_dll( load_path, filename, handle, flags, pwm );
```

**Comment by slackner** [comment]
sounds like a good idea. We should try to make clear that such a configuration is highly experimental, and can't work in all situations (name collisions, triggering insufficiencies of wine, ...). We could either use a winecfg configuration dialog, or a special environment variable.

**Comment by titan73** [comment]
"name collisions"?
Another big problem is we don't what's the default for each dll. We only can change the default. For me I prefer to have the default as builtin and add the overrides I need.
Yes it's for skilled people but the dlloverrides section is quite advanced in fact.
I like the purist mode because it forces me to knows all problem and fixed/reports them if possible. This also can lower a lot all those WINEPREFIX and winetricks gymnastic.

**Comment by slackner** [comment]
Wine only compares the dll basename when trying to figure out if should use a native implementation. This check can be wrong sometimes, for example when a developer thought its a good idea to call his library exactly like one of the system DLLs. Some other games also ship customized runtime DLLs (msvcrt, ....), when wine doesn't use them it can't work technically.

**Comment by slackner** [comment]
Since there wasn't any work on this idea during the last time I'll close this bug report. If someone is planning to work on this, patches would definitely be accepted. However, compared to other bugs it probably doesn't have a very high priority. ;)

**Comment by titan73** [comment]
Ok np. I'll do a patch soon.
