### ISSUE TITLE
Child of Light crash at launch

### ISSUE THREAD

**Issue by berillions** [wine-compholio/wine-staging#267]
I open a bug report here because on Wine bugzilla, there isn't help since the game is release.
The problem is that the game crash directly after to launch it in Uplay => We can see a white screen and the game cursor. 

I compared with real Windows and wine crash before the Ubisoft cinematic (when Ubisoft logo appears).
A bug report is create here : https://bugs.winehq.org/show_bug.cgi?id=36408

To test the game, a demo is available on Steam or directly on Uplay.

Thanks,
Max

**Comment by DarkPlayer** [comment]
I just tested the game and can confirm the problem. As tip for someone else trying to debug the issue: You should use Uplay directly instead of Steam, otherwise you need to have both, Steam and Uplay, running in order to test the game.

**Comment by berillions** [comment]
Are you sure for your edit ?

I download actually the demo directly from my UPlay account and i never download/install Steam before ou after.

**Comment by DarkPlayer** [comment]
For me the download of the Child of Light Demo finishes within seconds in Uplay and when I press install, the steam setup starts:

![uplay-steam](https://cloud.githubusercontent.com/assets/3102472/5715201/088157aa-9ad5-11e4-96b2-4189379be9af.png)

Maybe it is related to the location or the language, but in my case Uplay wants me to install Steam otherwise the installation fails.

**Comment by berillions** [comment]
If you want, i can to give you all log you needs.
Or try to put UPlay in English...

First time which I see that one demo on Uplay needs Steam. :/

**Comment by DarkPlayer** [comment]
I didn't give up yet on debugging this issue, but it is quite complicated. I need to restart Steam all the time and for some reason the game simply terminates when I enable relay as debug channel. I also can not attach a debugger, so I need to be creative in order to find the problem.

**Comment by DarkPlayer** [comment]
Debugging the application was really challenging, but I finally found the issue. I need to figure out what is the correct way to fix it, but with a workaround applied the game starts and is playable :-)

**Comment by DarkPlayer** [comment]
The issue should be fixed in 7c3eb208663b71fcc3669158aa7435b924df1e3e. Can you try the [patch](https://github.com/wine-compholio/wine-staging/blob/master/patches/netprofm-IConnectionPoint/0001-netprofm-Add-IConnectionPoint-INetworkListManagerEve.patch) with the original game to confirm that it does not only fix the demo?

**Comment by berillions** [comment]
Hi Michael,

I tried the patch with "Child of Light" and "Valiant Hearts".
Result = Both games work great with your patch.

Thanks :+1:

**Comment by slackner** [comment]
Nice to hear that it works. Did "Valiant Hearts" also have the same issue, which is also fixed by exactly this patch? I didn't find any upstream bugreport for that, unfortunately.

**Comment by berillions** [comment]
Yes "Valiant Hearts" had the same issue than "Child of Light", same crash at launch.

**Comment by berillions** [comment]
Sebastian / Michael, the patch for Child of Light will be implemented in Wine vanilla 1.7.35 ?

**Comment by slackner** [comment]
@berillions: We will try to do our best, but we cannot give any guarantees how fast patches get upstream. For Wine-Staging we can decide on our own if we consider patches good enough for inclusion, for upstream Wine we don't have any influence. Sometimes patches are accepted immediately, other times they are ignored, and sometimes even rejected without giving a good reason. Michael is currently still waiting for his previous patchset to get reviewed (http://source.winehq.org/patches/data/108376) and it is not recommended to submit too many patches at once, so you'll have to be patient a bit. This is also one of the main reasons why we started the staging tree, if fixes and new features would always get upstream easily there would be no need for that! ;)

Marking this bug as closed (for wine-staging).
