### ISSUE TITLE
Tomb Raider 2013 steam version automatic key input

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#279]
The game menu automatically scrolls down fast, without pressing any keys or using mouse cursor to select new game or some other option.

There is a known workaround.

"If you experience automatic key input in the main menu and game then delete any joystick from /dev/input: sudo rm /dev/input/js0"

Which I haven't tried. Also I remember people using some linux command that changes the delay of keyboard input or something like that.

Any idea how to debug this issue? Or what could cause it?

**Comment by Eignar17** [comment]
is it problem https://bugs.winehq.org/show_bug.cgi?id=33479

**Comment by Eignar17** [comment]
Is problem fix

**Comment by deri82** [comment]
This sounds a bit weird. I removed usb joustick trasmiter. The menu scrolls from bottom to top. When it's plugged it goes top to bottom.

**Comment by deri82** [comment]
moved to another bug tracker
