### ISSUE TITLE
Add support for CUDA 7.0

### ISSUE THREAD

**Issue by oscarbg** [wine-compholio/wine-staging#281]
Hi,
 just checking CUDA 7.0RC compiled SDK samples and running alignettypes I get :  ProgramData/NVIDIA Corporation/CUDA Samples/v7.0/bin/win64/Release/ WINEDEBUG=+nvapi,+nvcuvid,+nvcuda wine alignedTypes.exe 

getting errors like:
CUDA error at C:/ProgramData/NVIDIA Corporation/CUDA Samples/v7.0/6_Advanced/alignedTypes/alignedTypes.cu:281 code=46(cudaErrorDevicesUnavailable) "cudaMalloc((void **)&d_idata, MemorySize)" 

trace:nvcuda:Unknown1_func1_relay (0x240ea8, (nil))
...
detailed trace:
trace:nvcuda:DllMain (0x7ff867db0000, 1, (nil))
trace:nvcuda:wine_cuDriverGetVersion (0x2405b0)
trace:nvcuda:wine_cuInit (0)
trace:nvcuda:wine_cuGetExportTable (0x240588, 0x140025bc0)
trace:nvcuda:wine_cuGetExportTable (0x240590, 0x140025bd0)
trace:nvcuda:wine_cuDeviceGetCount (0x240c80)
trace:nvcuda:wine_cuDeviceGet (0x23f428, 0)
trace:nvcuda:Unknown1_func1_relay (0x240ea8, (nil))
trace:nvcuda:wine_cuDeviceGetName (0x240ee8, 256, 0)
trace:nvcuda:wine_cuDeviceTotalMem_v2 (0x240fe8, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241030, 75, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241034, 76, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241048, 15, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241120, 40, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24104c, 16, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241050, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241054, 18, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241058, 19, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241060, 21, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241064, 77, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241068, 69, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24106c, 22, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241070, 23, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241074, 73, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241078, 74, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24107c, 70, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241080, 71, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241084, 72, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241088, 45, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24108c, 46, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241090, 24, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241094, 25, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241098, 26, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24109c, 47, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410a0, 48, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410a4, 49, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410a8, 52, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410ac, 42, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410b0, 43, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410b4, 27, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410b8, 28, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410bc, 29, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410c0, 53, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410c4, 54, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410c8, 55, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410cc, 56, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410d0, 57, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410d4, 58, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410d8, 59, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410dc, 60, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410e0, 61, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410e4, 62, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410e8, 63, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410ec, 64, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410f0, 65, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410f4, 66, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410f8, 67, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x2410fc, 68, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241108, 31, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24110c, 32, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241110, 33, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241114, 34, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241118, 50, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24111c, 35, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241124, 41, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241128, 36, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24112c, 37, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241130, 38, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241134, 39, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f430, 30, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f438, 51, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f3d0, 8, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f3d4, 81, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x240ff8, 12, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241150, 82, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x240ffc, 10, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f3d8, 11, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241008, 1, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24100c, 2, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241010, 3, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241014, 4, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241018, 5, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24101c, 6, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241020, 7, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f3dc, 9, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241024, 13, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x23f3e0, 14, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241138, 78, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24113c, 79, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241140, 80, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241154, 83, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241158, 84, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24115c, 85, 0)
trace:nvcuda:Unknown2_func1_relay (0x2405a0, 0x23f460)
trace:nvcuda:Unknown2_func5_relay (0x2405a8, 0x23f468)
trace:nvcuda:wine_cuGetExportTable (0x240598, 0x140025be0)
trace:nvcuda:wine_cuGetExportTable (0x23f438, 0x140029208)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241050, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24105c, 20, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241024, 13, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241128, 36, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241050, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24105c, 20, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241024, 13, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241128, 36, 0)
trace:nvcuda:wine_cuCtxSetCurrent (0x7c723f10)
trace:nvcuda:wine_cuGetExportTable (0x23f730, 0x1400291f0)
trace:nvcuda:TlsNotifyInterface_Set (0x14003b9c0, 0x14000b230, (nil))
trace:nvcuda:wine_cuDeviceGetAttribute (0x241050, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24105c, 20, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241024, 13, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241128, 36, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241050, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x24105c, 20, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241024, 13, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x241128, 36, 0)
trace:nvcuda:ContextStorage_Get (0x23fa00, (nil), 0x24c2a0)
trace:nvcuda:wine_cuCtxGetCurrent (0x23f990)
trace:nvcuda:wine_cuCtxGetCurrent (0x23fa88)
trace:nvcuda:wine_cuCtxGetApiVersion (0x7c723f10, 0x23fa50)
trace:nvcuda:TlsNotifyInterface_Remove (0x1b560, (nil))

**Comment by slackner** [comment]
I have just written some patches for CUDA 7.0 support, you can find them on our new bug tracker: https://bugs.wine-staging.com/show_bug.cgi?id=51
The patch depends on CUDA 6.5 support, you first have to apply all the nvcuda-* patches here in our repository.

Unfortunately I do not have all the necessary tools to compile the CUDA 7.0 SDK examples on Windows. Could you maybe provide them in a compiled form? As soon as some testing was done these patches can be added.

**Comment by slackner** [comment]
Someone helped me testing, and the patchset seems to work as expected. This issue is fixed with 39787f3608955ec12da0eb971ee097fb27da4ca5.
