### ISSUE TITLE
windowscodecs: Fix init of LONGLONG variable with a negative value in TGA decoder

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#282]
Patch is here http://ix.io/fMp.

sizeof() is unsigned and thus -sizeof() too which leads to the signed bit not propagated when converted to LONGLONG. This bug prevented the footage header to be found which contains the TGA spec 2.0 extension.

**Comment by slackner** [comment]
Added in 3e7445275ab9405e5ab43bbe2bdd624fed24ccb6.
Nice catch! ;)
