### ISSUE TITLE
UPlay games + Prefix 64-bits + WinVista/7 = Error

### ISSUE THREAD

**Issue by berillions** [wine-compholio/wine-staging#284]
As i explained in this bugreport  : 
https://bugs.winehq.org/show_bug.cgi?id=33776

it's impossible to launch a game in this configuration. With Qian Hong's help, we found that the problem come from IsWow64Process which fails (comment #8) and his hack works properly with actual Directx9 games.

I create this issue because the new Directx11 games will use only 64-bits system so i think it's a good thing to resolv this bug with 32-bits games.

You have the possibility to donwload/install "Child of Ligth" demo to test, the demo does not work without the hack.

Max

**Comment by slackner** [comment]
Qian Hongs patch is currently waiting for review on the wine patches mailinglist ( http://source.winehq.org/patches/ ), see:

http://source.winehq.org/patches/data/108619

We will wait a bit before adding it, if it gets upstream immediately there is no need to include it in this repo. If its not fixed till 1.7.35 we will add it.

**Comment by berillions** [comment]
As i said in the bug report, the Qian's patch does not fix the problem.
The game still not works on 64-bits prefix + WinVista/7. 

The Hack still works.

**Comment by slackner** [comment]
Hm, I got that impression because Qian explicitly mentioned in his patch that it was supposed to fix this issue.

Please try out his new second patch ( https://bugs.winehq.org/show_bug.cgi?id=33776#c29 ), in addition to the first one which is already included upstream:
https://bugs.winehq.org/attachment.cgi?id=50491

**Comment by slackner** [comment]
Was just marked as fixed upstream. Can you confirm that this problem no longer exists? If yes we can also close this one.

**Comment by slackner** [comment]
Assuming this is fixed.
