### ISSUE TITLE
d3dx9_36: Implement D3DXCreateAnimationController with a stubbed  ID3DXAnimationController interface

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#289]
The patch is here http://ix.io/fPM.
ID3DXAnimationController is used by Secret Files 3.

**Comment by slackner** [comment]
Added in 294abd91647ab733d4dac2c671feface38715e0f. :)

**Comment by titan73** [comment]
@slackner: I forgot add these few changes http://ix.io/fQf. Can you merge them with the patch?

**Comment by slackner** [comment]
Added in 417adfe869c721c7a31b29a68bae6bdcf020295a.
