### ISSUE TITLE
=================================================

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#292]
We decided that its time to move to a more advanced bug tracker. Please do not open any new bugs in this one anymore. If you have reported an issue in the past, don't worry - we will of course keep your bug report open for now.

### [--> Go to the new bugtracker <--](https://bugs.wine-staging.com)

--------------------------------

##### More detailed information

We were a bit unhappy about the github bugtracker for a long time now. One of the main disadvantages for unexperienced users was the lack of file attachments. As the number of contributors and users is steadily increasing we decided to setup our own server exclusively used for wine-staging.com, including a bugzilla instance. Since we didn't have any time for extensive testing yet, it might be possible that you'll still encounter issues. Please report them to us, for example via email to `webmaster [AT] wine-staging [DOT] com`. We are aware that SSL is still a bit slow, probably caused by the used encryption - we will try to optimize that a bit during the next days.

Please note that we'll no longer accept bug reports in this bug tracker, so every newly created bug report will be closed with a link to this issue, without further investigation. I already discussed with @DarkPlayer how to deal with existing bugs, and we think that it makes sense to keep "real" existing bug reports here (for example issues reported by users, issues with a long discussion, ...). For issues which were ignored so far (for example suggestions for specific upstream bugreports we could take a look at) we will decide for each one individually.

@compholio @titan73: Feel free to help moving bug reports (mainly upstream wine issues which don't have any comments so far) to the new bug tracker. If you are unsure if it makes sense to move them, feel free to discuss this in the corresponding bug report. We should try to avoid moving just everything, otherwise we'll end up with a lot of "dead" bugs again. Sooner or later this will happen anyway, but now we have the chance to avoid it. Criterias we should use:

* is there a known patch? has someone already figured out what exactly has to be fixed?
* how difficult would it be to fix the issue?
* how important is the corresponding bug? when only a single user is affected, it might not be worth spending several hours/days of debugging

@DarkPlayer: Could you please add one more custom field "Upstream Bug Id" to save this information in a bit more database-friendly format?

If you want to test things on the new bug tracker, you can use [bug 1](https://bugs.wine-staging.com/show_bug.cgi?id=1) for that.

**Comment by DarkPlayer** [comment]
The issues regarding the performance should be fixed now.

**Comment by compholio** [comment]
@slackner: I made a list of "analyzed" bugs the other day, I'll go ahead and move them over.

**Comment by i30817** [comment]
I think this is a mistake and you'll get far less reports and comments with a project specific bug tracker. Files can be simply linked to a user google drive.

**Comment by slackner** [comment]
@i30817: It is unfortunately not really possible to find a suitable solution for everyone, I fear. Whereas from a regular user perspective a "forum-like" bugtracker like Github is probably absolutely fine, it is not always the easiest solution for advanced users and developers. Please keep in mind that for short questions people can still hop on IRC, and ask their question there, if they don't want to register an account - and for more difficult problems we will always need logs, detailed information about the wine version, what was tested so far, probably screenshots if its a graphical problem, and so on. We also have no possibility to ask the user for more information here on Github before opening a bug report, I guess almost noone read our bug reporting guidelines so far. We already had multiple users who ran into issues because they were more used to "regular" bugtrackers, and confused by the Github interface. Most people reporting issues here actually do not come from the upstream Wine bugtracker, but instead are opened by Fedora users (where WIne-Staging is packaged as default Wine version).

This wasn't a decision we made in a couple of minutes, we've been thinking and discussing about doing this step for a while (at least several months) now, and I still think it was the right decision so far. Besides the issue with file attachments this bugtracker also got flooded with huge amount of upstream bugs, which in theory is not really a problem. But it got a bit problematic when we had so many of them, that we can't really distinguish between important and less important ones. In the new bugtracker all such upstream issues are  in a separate component, and we have much better method to define for example priorities. We haven't finished configuring everything yet, but as soon as this is done, it will hopefully allow us again to focus on more important parts like doing actual development work, instead of being frustrated about missing bugtracker features. ;)

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
