### ISSUE TITLE
Sugestion: A possible Android x86 port of Wine Staging

### ISSUE THREAD

**Issue by Arucard1983** [wine-compholio/wine-staging#296]
Actually on Android x86 tablets it's possible to install GnuRoot or Debian noroot from Google Play and set a chrooted Debian without rooting the device using a user-mode root syscall emulator called proot.
However sound are not supported, and OpenGL was recently unsupported until a new library called glshim enable a basic OpenGL ES translator to the standard OpenGL 1.x.
Later a Russian company also launch is own port of an ARM to x86 emulator (Exagear), and uses a small Linux distro with x86 Wine to run some old games and applications. The application itself is a front-end that hides the start-up of their own proprietary emulator and Wine until a X11 windows pop-ups and runs the actual Windows program.
 So it's possible to do a port of your Wine Staging, packed with the X11 Server from Pelya or Darkside, both open-source (It's a X11 Server for Android), adding sound support, the proot and some Debian libraries, and launch it as an Android x86 application ?
(The not so trivial task was the writting of the Java front-end itself.)
I think if someone picks this task would be a game changer on Android x86 tablets, and could be more easy to run Windows applications without installing a full Linux environment.

**Comment by DarkPlayer** [comment]
As written in #292 we moved our bug tracker to https://bugs.wine-staging.com and don't accept any new bug reports here. Please open a bug in our new bug tracker (Component: Discussion).

I could write a long answer, but it does not make sense, since the bug report / question doesn't belong here and will be closed.
