### ISSUE TITLE
fast upload :D

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#297]
![snapshot4](https://cloud.githubusercontent.com/assets/3125379/5902404/e6b2922a-a582-11e4-9a26-74f7bf2d9b6d.png)

**Comment by deri82** [comment]
![snapshot5](https://cloud.githubusercontent.com/assets/3125379/5902452/2ee8e1fc-a583-11e4-8ae7-c61b959d12db.png)

**Comment by titan73** [comment]
Air strike was one of my test games for implementing DXT texture and DrawText! ;)

**Comment by slackner** [comment]
@deri82: Would you mind documenting the differences on the corresponding upstream bug report?

I assume this issue was just opened for quickly showing the images, so closing again. ;)
