### ISSUE TITLE
The Sims 4 can not be installed due to the installer failing to install vcrun2013

### ISSUE THREAD

**Issue by steve7233** [wine-compholio/wine-staging#298]
I am using PlayOnlinux - POL - version 4.2.5. I tried usig wine 1.7.35 to install Origin>The Sims 4. Origion works and downloads The Sims 4. The Sims 4 installer runs then errors out. When I looked at the Sims 4 Log it said vcrun failed with error code 5. The POL devs said that If you have a patch that will work then they just need to know the name of the patch and then they will package a version of wine 1.7.35 with the patch for POL.

**Comment by titan73** [comment]
Hi @steve7233. The bug tracker has moved to https://bugs.wine-staging.com. Open a new bug there.

**Comment by deri82** [comment]
SimCity4 Deluxe Installer updated with Steam support

Friday 23 January 2015 at 23:41 (0 comments)

The installer for SimCity 4 Deluxe has been updated to use the newest version of Wine, as well as having added Steam support for newer purchasers of this fantastic, old-school game.

Enjoy!


MiniatureMiniature


Check it out here:
http://www.playonlinux.com/en/app-311.html

**Comment by titan73** [comment]
@steve7233: if you intend to target games, you'd better consider using the whole wine-staging patchset.
