### ISSUE TITLE
word of warcraft test

### ISSUE THREAD

**Issue by roboso** [wine-compholio/wine-staging#318]
after three days of testing .. 
1) in raids sometimes stops the game for a few seconds ... do not know why but the fps suddenly fall to 5 and then back to 20-25 
2) the cpu gets to temperature values impressive ... last night came after a session raid of two hours and a half ... at 73-76 ° C .... 

script start: 
force_s3tc_enable=true taskset -c 0,1,2,3 /opt/wine-staging/bin/wine64 wow/Wow-64.exe

**Comment by roboso** [comment]
![ajaj_ipgh8cytpfdif00rfmiixmgtoxd6wmnbild63cu](https://cloud.githubusercontent.com/assets/6564204/7186365/6fc47f2c-e469-11e4-92c1-b9c72011cf86.jpg)

**Comment by DarkPlayer** [comment]
We do not accept new bug reports on this bug tracker any more. Please use our new bug tracker at  https://bugs.wine-staging.com instead.

Moreover the frame drop you encounter is most probably related to the high temperature, i.e the graphic card or cpu is reducing the clock frequency to prevent a terminal damage. The cpu usage of 200% (with 4 cores) doesn't seem to be unusual and there is most probably nothing to fix in Wine. You should instead fix the overheating problems of your pc.
