### ISSUE TITLE
WIKI page is incomplete for compiling Wine-staging on 64bit system

### ISSUE THREAD

**Issue by roadapathy** [wine-compholio/wine-staging#319]
I emailed both maintainers of Wine and Wine-staging for the Ubuntu repositories but I didn't get a reply from either one. Xubuntu 15.04 64 bit does not seem to compile and install Wine 64 and wine 32 bit. I can compile Wine 64bit perfectly but it is useless without 32. I have no idea why, but I'm not a developer who could understand anyway.

If I can get help with the building and installation process, I would like to volunteer an update to the Wiki page. I'm a liberal arts student, not a programmer, so I could write the guide for the average user.

This is a last resort. I have used every guide on WineHQ and around the web. 32 bit compiling process always complains about missing libs, but these files appear in the correct directories. Even after I symbolically link them further, it still complains bitterly about missing files.

Next, I will just install 32bit Xubuntu 15.04 on another partition and use it there. Steam sale is going to be TODAY so we're really missing an opportunity here to spread the word of Linux awesomeness.

Thanks!

**Comment by slackner** [comment]
Hello,

first of all, you somehow missed that we do not accept further bug reports here directly at github. All remaining opened bug reports are slowly moved to our new dedicated bugtracker located at https://bugs.wine-staging.com/, so if you have any additional questions or problems, please open your bugs there instead. Normally we would close bugs here immediately, nevertheless I'll make an exception and answer here in this case.

Where did you send your request regarding Wine/Wine-Staging? I quickly asked the other developers, and noone received anything. You either tried to contact the wrong person, or your mails got lost somehow.

Regarding your main question, compiling 32-bit Wine on a 64-bit machine is indeed a bit difficult. Theoretically it should be sufficient to have all 32-bit dependencies installed, but unfortunately various dependencies of Wine are not completely multiarch ready, which means the package manager doesn't allow to install the 32-bit and 64-bit version at the same time. The easiest and most reliable way to solve that is to compile Wine in an 32-bit LXC container or chroot, the following Wiki page contains detailed information how to do this: http://wiki.winehq.org/BuildingBiarchWineOnUbuntu . If you are already aware of this way to build wine, but it still doesn't work, please provide more details about what exactly doesn't work, including a log with terminal output / the compile errors, if possible.

Nevertheless, one thing I am wondering about: I hope you are aware that we are also providing prebuilt Wine Staging packages in our own Ubuntu PPA. Information about how to install it, can be found here: https://github.com/wine-compholio/wine-staging/wiki/Installation#-ubuntulinux-mint . Is there any reason why you want to build it yourself?

Regards,
Sebastian

**Comment by roadapathy** [comment]
Hello! I sent an email to Scott Ritchie, who maintains the Wine repository for Canonical and I emailed Erich Hoover, the maintainer of Wine-staging repository. Of course, my email was polite so I can't imagine they would first delete it. They work hard and I know it, so I keep my own frustrations separate.

 I tried today the LXC method, but it failed too. Could I instead just compile onto 32 bit Xubuntu that I put on another partition? I can boot to any Ubuntu version.

These were the instructions that I had been using. Everything with the 64 bit works fine, but using 32 bit causes failed dependencies, even though I see the files inside the i386 directories! 

wget http://prdownloads.sourceforge.net/wine/wine-1.7.*.tar.bz2 
wget https://github.com/wine-compholio/wine-staging/archive/v1.7.*.tar.gz
tar xvjf wine-1*.tar.bz2
cd wine-1*
tar xvzf ../v1.7.44.tar.gz --strip-components 1
./patches/patchinstall.sh DESTDIR="$(pwd)" --all
cd ..
mkdir wine64
cd wine64
../wine-1.7.44/configure --with-xattr --prefix=/opt/wine-staging3 CFLAGS="-O3 -march=bdver2" CXXFLAGS="-O3 -march=bdver2" --without-cups --without-sane --with-opencl --without-oss --without-pcap --without-hal --enable-win64
make -j6
cd ..
mkdir wine32
cd wine32
../wine-1.7.44/configure --with-xattr --prefix=/opt/wine-staging3 CFLAGS="-O3 -march=bdver2" CXXFLAGS="-O3 -march=bdver2" --without-cups --without-sane --with-opencl --without-oss --without-pcap --without-hal --with-wine64=../wine64

**Comment by roadapathy** [comment]
If you notice, I have very aggressive optimizations for my specific CPU. This is why I prefer to use this version over the ones in the PPA. Many Windows games run terrible even on Windows, so I was hoping to have the Linux advantage... because Linux is the gaming OS of the future, says Gabe Newell.

**Comment by compholio** [comment]
Wow, you totally emailed me and I didn't notice it.  And I don't even have the excuse that it was on my honeymoon since it was only three days ago.  I'm really sorry about that!

**Comment by compholio** [comment]
Looking over your email it's looking like you have some conflicts in your installed packages that is preventing you from installing wine-staging.  Could you run "sudo apt-get install wine-staging" from a terminal and see what it says?

**Comment by roadapathy** [comment]
Oh, now I feel bad but I didn't want to email you at all except that I was pretty desperate. I think I hate fought with the installation and building process for a few weeks, maybe months. Wine-staging project is completely new to me! I can't believe it. It's a great project!

I have been able to get Wine-staging to install. It ran an OpenGL Windows game that has never worked before. However, it ran slow and I wanted to build the project and produce a Wiki page for others like me. That didn't work and now here I am.

The conflicts in my install packages is now solved. I reinstalled Xubuntu 15.04. The strange thing is this: I booted to Xubuntu, Kubuntu and Ubuntu 15.04 and tried to install onto the live USB but it didn't work. It's working now on my main system but that may be because I installed updates first.

**Comment by roadapathy** [comment]
Oh, and my most aggressive optimizations are here. Whether they work or not, I don't know, but I used something similar for my Kernel and it compiled and ran fine:

./configure CPPFLAGS="-I/usr/local/cuda/include/" LDFLAGS="-L/usr/local/cuda/lib" CFLAGS="-O3 -march=bdver2 -lcuda -lcudart -lcusparse -lcublas" CXXFLAGS="-O3 -march=bdver2 -lcuda -lcudart -lcusparse -lcublas" --with-opencl --without-oss --enable-win64

If it works, I almost think some Windows games would run faster in Linux than in Windows because of this plus the vastly superior EXT4 vs NTFS.

**Comment by roadapathy** [comment]
Erich, congratulations on your marriage and a successful project with annoying, but hopefully helpful, users like me.

**Comment by compholio** [comment]
I'm glad you got the package figured out, I'm really sorry that I dropped the ball on that one.  Ok, so now you want to compile yourself - which totally makes sense.  The easiest way to do this on Debian-based distros is to install the build dependencies for the package (for example: sudo apt-get build-dep wine).  However, as you are now aware, building Wine on 64-bit is rather tricky.  I have a package to help with this, though it might not be updated to include everything at this point.  The directions for using it are located here:
http://wiki.winehq.org/WineOn64bit#head-7ec17a02cb62e99f75e40890fee9e6c1cb2139c9

**Comment by slackner** [comment]
Just a remark regarding various of the optimization flags. Linking against cuda/cudart/... and various other libs will most likely not bring any speed improvement, because Wine doesn't use it. `-O3` will have the biggest effect I assume, but it also brings the risk of breaking certain applications - in general compiler optimization never works that well for Wine, but you will have to try it out of course.

**Comment by roadapathy** [comment]
Erich, I used your symbolic link trick. It's the best solution and got me further than any other guide but it still produced failures even though I could see the libs in the i386 directories. I added to it, but not very well. I thought about compiling each component that fails but I'm not sure how to compile to 32 bit. I thought Wine-staging only needs the .h files.

**Comment by roadapathy** [comment]
Slackner, I think that you're correct. I know that -O3 and -march=bdver2 works very well, because this works toward my specific CPU but I also use GCC 5.1 rather than the 4.9.2 that comes with Ubuntu. Everything beyond that is risky.

**Comment by slackner** [comment]
Using gcc 5.1 is a bad choice because this definitely leads to problems when optimization is enabled - see: https://bugs.winehq.org/show_bug.cgi?id=38653

**Comment by roadapathy** [comment]
Ok, maybe I should first attempt this project on a fresh installation of Xubuntu and use only the provided GCC. I want to mention that GCC 5.1 works perfectly on Kernel 4.x and 4.1.x even with aggressive optimizations. What do you honestly think? I have used it + kernel for weeks now and no issues.

**Comment by roadapathy** [comment]
Erich and Slckner, I think I will begin this project with a fresh Xubuntu 15.04 and use your advice. I should stay with GCC 4.9.2 and only use -O2 or -O3 along with -march=bdver2.

Should I produce 32 bit libs using Xubuntu 32 bit and then copy them to the 64 bit Xubuntu?
Should I instead compile each missing lib myself? For this, I don't know what options to use. I wonder if this is the -m32 or -march=i386. This is beyond my scope.

I could add more to Erich's symbolic link solution to match my system, possibly. Then after success, simply create the guide for others. For example, my guides are here: http://compilestuff.blogspot.com/

**Comment by slackner** [comment]
> Erich and Slckner, I think I will begin this project with a fresh Xubuntu 15.04 and use your advice. I should stay with GCC 4.9.2 and only use -O2 or -O3 along with -march=bdver2.

Sounds like a good idea, with gcc 4.9 this bug shouldn't occur.

>Should I produce 32 bit libs using Xubuntu 32 bit and then copy them to the 64 bit Xubuntu?
Should I instead compile each missing lib myself? For this, I don't know what options to use. I wonder if this is the -m32 or -march=i386. This is beyond my scope.
>
>I could add more to Erich's symbolic link solution to match my system, possibly. Then after success, simply create the guide for others. For example, my guides are here: http://compilestuff.blogspot.com/


What do you mean with "produce libs"? What you could do is to compile 64-bit WIne on a Xubuntu 64-bit machine, and to compile 32-bit Wine on a 32-bit machine. Afterwards you basically just have to copy them on top of each other (the 64-bit version on top of the 32-bit version), and you should get a proper wow64 build.

Alternatively you can also try the LXC method or Erichs solution again. I used the LXC method myself some time ago, and it worked well. As you already found out above, header files alone are not sufficient, you really need the 32-bit libs. When they are installed it should normally work fine.

**Comment by roadapathy** [comment]
Slackner: Ahhh ok. So to be clear, you're saying I can build on 32 bit Ubuntu, then simply copy the 32 bit wine over to 64 bit Ubuntu? Also, do I add the dependent 32bit libs from 32 bit OS over to 64 bit OS's /usr/lib/i386/i386-linux-gnu directory? I hope I understand this right.

**Comment by compholio** [comment]
@roadapathy You should be able to just install my debian package, but if there are additional missing symlinks then if you let me know then I can add them.

**Comment by roadapathy** [comment]
Ok, I will work on this today. I have had much coffee and it is my day off. So let it begin!

**Comment by roadapathy** [comment]
Erich, this does not install on Vivid. I think 15.04 is too new?

sudo apt-add-repository ppa:ehoover/compholio
sudo apt-get update
sudo apt-get install ia32-libs-dev

**Comment by compholio** [comment]
I haven't compiled for Vivid yet, you could try installing the Trusty version:
https://launchpad.net/~ehoover/+archive/ubuntu/compholio/+build/6003353/+files/ia32-libs-dev_3.0.0%7Eubuntu14.04.1_amd64.deb
(sudo dpkg -i ia32-libs-dev_3.0.0~ubuntu14.04.1_amd64.deb)

**Comment by roadapathy** [comment]
I had an idea but it would take some time and I don't want to start it if we already know it doesn't work:

Could simply add files from my 32 bit Xubuntu into my 64 bit Xubuntu's /lib/usr/i386 directory?

The other option I thought about is to compile the libs, create a special directory just for them and then add that directory location to /etc/etc/ld.so.conf.d/joels32bitlibs.conf

I will have time tonight to work on this.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
