### ISSUE TITLE
Silverlight sites don't work on 1.7.49

### ISSUE THREAD

**Issue by ZDroid** [wine-compholio/wine-staging#323]
I am facing a lot of network issues related to Silverlight sites. I am using latest version of Pipelight and Campholio. If you try to load some dynamic content, it works fine for a few minutes and then disconnects for 15-30 seconds. All other sites work fine. I tested my connection and Silverlight on Windows, both work fine so I think it isn't up to site or up to my connection.

It stopped working after I updated my packages yesterday and one of updates was Wine Compholio 1.7.49.

**Comment by DarkPlayer** [comment]
As you can see on the issue overview list, the Wine Staging bug tracker has been moved to https://bugs.wine-staging.com/ 7 months ago and we do not accept any bug reports here.

Moreover, your issue is more related to Pipelight, so the correct side would be: https://launchpad.net/pipelight
