### ISSUE TITLE
So i have steam on wine and i bought sims 3 but it wont run.

### ISSUE THREAD

**Issue by cupcakecool** [wine-compholio/wine-staging#324]
But it says error and here is what it says when i click infomation. It said this can be caused by problem in the program or deficiency in wine you may want to check the application database for tips about running this application. So i clicked that and it took me to this page where it said this. What works
Installing from steam
Playing the game
Installing mods 
installed steam via play on linux 
Launches SIMS launcher when launched in steam (Starting game and Downloading mods from launcher is buggy)

What does not
Nothing that i can think of

What was not tested
I think i covered everything

Additional Comments
ASUS K84l 
Intel HD graphics 3000 
Core i3-2350M Dual-Core 2.3GHz 
4GB RAM 320GB space
There was a couple of graphical glitches within builing/placing stuff.
I had to install sims 3 from steam because i bought the digital copy
Installed d3dx9 dotnet20 dotnet 30sp1 msxml3 tahoma vcrun2005 (and other dependencies for other games) If i missed any other Packages please let me know
Test Results
Distribution Test date Wine version Installs? Runs? Rating Submitter
Show Ubuntu 15.04 "Vivid" amd64 (+ variants like Kubuntu) Aug 06 2015 1.7.48 Yes Yes Silver Heisenbug
Current Linux Mint 17.1 "Rebecca" x86-64 Jun 05 2015 1.7.44 Yes Yes Platinum Rangerwolf 
Show Ubuntu 14.04 "Trusty" amd64 (+ variants like Kubuntu) Mar 26 2015 1.7.34 Yes Yes Platinum Weisser Helge 
Show Arch Linux x86_64 Sep 14 2014 1.7.26 Yes Yes Platinum an anonymous user 
Show DeepIn Linux 2014 Aug 06 2014 1.7.23 Yes Yes Gold an anonymous user 
when i clicked show details it said all this. Unhandled exception: page fault on execute access to 0x00000000 in 32-bit code (0x00000000).
Register dump:
CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
EIP:00000000 ESP:0064ccec EBP:00000000 EFLAGS:00010246( R- -- I Z- -P- )
EAX:00000000 EBX:00000000 ECX:0064cbdc EDX:00000000
ESI:00000000 EDI:00000000
Stack dump:
0x0064ccec: 7b2409b5 7b33df7c 00000000 0064cd68
0x0064ccfc: 000004b6 7b23bc9e 7b33df7c 7b24418b
0x0064cd0c: 7b33df7c 7a3b509d 7b33df7c 797bf8eb
0x0064cd1c: 7b33df7c 7b633890 7b633704 7e226bb0
0x0064cd2c: 796602a1 7a3b584d 7b633704 7b633890
0x0064cd3c: 7b2453b8 7a7bcaa3 00000000 7a8e1064
Backtrace:
=>0 0x00000000 (0x00000000)
0x00000000: -- no code accessible --
Modules:
Module Address Debug info Name (98 modules)
PE 400000- 482000 Deferred steamerrorreporter
PE 3f000000-3f111000 Deferred tier0_s
PE 3f600000-3f654000 Deferred vstdlib_s
ELF 79139000-7b800000 Deferred fglrx_dri.so
ELF 7b800000-7ba61000 Deferred kernel32
-PE 7b820000-7ba61000 \ kernel32
ELF 7bc00000-7bce2000 Deferred ntdll
-PE 7bc10000-7bce2000 \ ntdll
ELF 7bf00000-7bf03000 Deferred 
ELF 7d5c5000-7d5e3000 Deferred libatiuki.so.1
ELF 7d5e3000-7d600000 Deferred libgcc_s.so.1
ELF 7d6e9000-7d861000 Deferred libvorbisenc.so.2
ELF 7d861000-7d895000 Deferred libflac.so.8
ELF 7d895000-7d907000 Deferred libsndfile.so.1
ELF 7d907000-7d976000 Deferred libpulsecommon-4.0.so
ELF 7d976000-7d9c5000 Deferred libpulse.so.0
ELF 7d9c5000-7d9dd000 Deferred libresolv.so.2
ELF 7d9dd000-7da28000 Deferred libdbus-1.so.3
ELF 7da28000-7da64000 Deferred libp11-kit.so.0
ELF 7da64000-7db98000 Deferred libx11.so.6
ELF 7dbd9000-7dc5e000 Deferred libgcrypt.so.11
ELF 7dc5e000-7dc70000 Deferred libtasn1.so.3
ELF 7dc70000-7dca0000 Deferred libk5crypto.so.3
ELF 7dca0000-7dca6000 Deferred libxfixes.so.3
ELF 7dca6000-7dcb1000 Deferred libxcursor.so.1
ELF 7dcb1000-7dcc1000 Deferred libxi.so.6
ELF 7dcc1000-7dcc5000 Deferred libxcomposite.so.1
ELF 7dcc5000-7dcd0000 Deferred libxrandr.so.2
ELF 7dcd0000-7dcdb000 Deferred libxrender.so.1
ELF 7dcdb000-7dce1000 Deferred libxxf86vm.so.1
ELF 7dce1000-7dce8000 Deferred libxdmcp.so.6
ELF 7dce8000-7dd0a000 Deferred libxcb.so.1
ELF 7dd0a000-7dd1d000 Deferred libxext.so.6
ELF 7dd1d000-7ddb0000 Deferred winex11
-PE 7dd30000-7ddb0000 \ winex11
ELF 7ddb1000-7ddb8000 Deferred libffi.so.6
ELF 7ddb8000-7ddbd000 Deferred libgpg-error.so.0
ELF 7ddbd000-7ddc1000 Deferred libkeyutils.so.1
ELF 7ddc1000-7ddcd000 Deferred libkrb5support.so.0
ELF 7ddcd000-7ddd2000 Deferred libcom_err.so.2
ELF 7ddd2000-7de90000 Deferred libkrb5.so.3
ELF 7de90000-7df59000 Deferred libgnutls.so.26
ELF 7df59000-7df9e000 Deferred libgssapi_krb5.so.2
ELF 7df9e000-7e00b000 Deferred libcups.so.2
ELF 7e00d000-7e039000 Deferred libvorbis.so.0
ELF 7e039000-7e0be000 Deferred rpcrt4
-PE 7e040000-7e0be000 \ rpcrt4
ELF 7e0be000-7e200000 Deferred ole32
-PE 7e0e0000-7e200000 \ ole32
ELF 7e301000-7e313000 Deferred libavahi-client.so.3
ELF 7e313000-7e321000 Deferred libavahi-common.so.3
ELF 7e32b000-7e334000 Deferred libogg.so.0
ELF 7e334000-7e33b000 Deferred libasyncns.so.0
ELF 7e33b000-7e345000 Deferred libwrap.so.0
ELF 7e345000-7e350000 Deferred libjson-c.so.2
ELF 7e350000-7e399000 Deferred dsound
-PE 7e360000-7e399000 \ dsound
ELF 7e399000-7e400000 Deferred dbghelp
-PE 7e3a0000-7e400000 \ dbghelp
ELF 7e502000-7e506000 Deferred libxinerama.so.1
ELF 7e506000-7e50a000 Deferred libxau.so.6
ELF 7e530000-7e554000 Deferred imm32
-PE 7e540000-7e554000 \ imm32
ELF 7e59d000-7e5c6000 Deferred libexpat.so.1
ELF 7e5c6000-7e601000 Deferred libfontconfig.so.1
ELF 7e601000-7e629000 Deferred libpng12.so.0
ELF 7e629000-7e6c9000 Deferred libfreetype.so.6
ELF 7e6ec000-7e713000 Deferred mpr
-PE 7e6f0000-7e713000 \ mpr
ELF 7e713000-7e72c000 Deferred libz.so.1
ELF 7e72c000-7e7aa000 Deferred wininet
-PE 7e740000-7e7aa000 \ wininet
ELF 7e7aa000-7e7bd000 Deferred psapi
-PE 7e7b0000-7e7bd000 \ psapi
ELF 7e7bd000-7e837000 Deferred shlwapi
-PE 7e7d0000-7e837000 \ shlwapi
ELF 7e837000-7ea6f000 Deferred shell32
-PE 7e840000-7ea6f000 \ shell32
ELF 7ea6f000-7eae0000 Deferred advapi32
-PE 7ea80000-7eae0000 \ advapi32
ELF 7eae0000-7ebff000 Deferred gdi32
-PE 7eaf0000-7ebff000 \ gdi32
ELF 7ebff000-7ed5c000 Deferred user32
-PE 7ec10000-7ed5c000 \ user32
ELF 7ed5c000-7ed69000 Deferred libnss_files.so.2
ELF 7ed69000-7ed75000 Deferred libnss_nis.so.2
ELF 7ed75000-7ed8e000 Deferred libnsl.so.1
ELF 7ed8e000-7ed97000 Deferred libnss_compat.so.2
ELF 7ef97000-7efdd000 Deferred libm.so.6
ELF 7efe7000-7f000000 Deferred version
-PE 7eff0000-7f000000 \ version
ELF f73e3000-f73ec000 Deferred librt.so.1
ELF f73ed000-f73f2000 Deferred libdl.so.2
ELF f73f2000-f75a0000 Deferred libc.so.6
ELF f75a0000-f75bc000 Deferred libpthread.so.0
ELF f75e0000-f7796000 Dwarf libwine.so.1
ELF f7798000-f77ba000 Deferred ld-linux.so.2
ELF f77ba000-f77bb000 Deferred [vdso].so
Threads:
process tid prio (all id:s are in hex)
0000000e services.exe
0000001d 0
0000001c 0
00000014 0
00000010 0
0000000f 0
00000012 winedevice.exe
0000001b 0
00000018 0
00000017 0
00000013 0
00000019 plugplay.exe
0000001f 0
0000001e 0
0000001a 0
00000020 explorer.exe
00000021 0
00000061 (D) C:\Program Files\Steam\steamerrorreporter.exe
00000066 0
00000065 0
00000064 0 <==
00000063 0
00000062 0
System information:
Wine build: wine-1.7.33
Platform: i386
Host system: Linux
Host version: 3.13.0-37-generic
And i also installed wine 1.7.44 cause it said that on the page. i dont know if that helped which it didnt haha i have so many problems with this kind of stuff. any help can be used.

**Comment by cupcakecool** [comment]
Gee so much for help -_-  -.-

**Comment by DarkPlayer** [comment]
As you can see on the issue overview list, the Wine Staging bug tracker has been moved to https://bugs.wine-staging.com/ 7 months ago and we do not accept any bug reports here.
