### ISSUE TITLE
SetEndOfFile should be successful when there are mappings...

### ISSUE THREAD

**Issue by mustrumr** [wine-compholio/wine-staging#327]
but only when it is trying to enlarge the file. https://msdn.microsoft.com/en-us/library/windows/desktop/aa365531%28v=vs.85%29.aspx#2

**Comment by slackner** [comment]
Thanks for reporting this issue. The bug was fixed in https://github.com/wine-compholio/wine-staging/commit/d4e35818474956f37beae0f3f60378f72b160aab (before the 1.7.54 release).
