### ISSUE TITLE
Cannot start voobly with the latest version

### ISSUE THREAD

**Issue by SRGOM** [wine-compholio/wine-staging#329]
Voobly v2.2.4.38
Stacktrace:

    fixme:win:FlashWindowEx 0x32d880 - semi-stub
    fixme:ieframe:WebBrowser_QueryInterface (0x171758)->({b722bcc5-4e68-101b-a2bc-00aa00404770} 0x32c948) interface not supported
    fixme:ieframe:PersistStreamInit_InitNew (0x171758)
    fixme:ieframe:OleObject_Advise (0x171758)->(0x140b2c0, 0x140b2e4)
    fixme:ieframe:ViewObject_SetAdvise aspects and/or flags not supported yet
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -701
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -704
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -709
    fixme:ieframe:ConnectionPointContainer_EnumConnectionPoints (0x1718b0)->(0x32c308)
    Object::connect: No such signal QAxWidget::BeforeNavigate() in ../common/browserview.cpp:66
    Object::connect:  (sender name:   'activeX')
    Object::connect:  (receiver name: 'BrowserView')
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:OleControl_OnAmbientPropertyChange Unknown dispID -703
    fixme:ieframe:navigate_url Unsupported args (Flags 0x14ea38 {VT_I4: 0}; TargetFrameName 0x14ea48 {VT_BSTR: L""})
    fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
    fixme:urlmon:InternetBindInfo_GetBindString not supported string type 12
    fixme:win:FlashWindowEx 0x32ae60 - semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:IsDomainLegalCookieDomainW (L"voobly.com", L"www.voobly.com") semi-stub
    fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
    err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
    Qt has caught an exception thrown from an event handler. Throwing
    exceptions from an event handler is not supported in Qt. You must
    reimplement QApplication::notify() and catch all exceptions there.

    fixme:dbghelp:elf_search_auxv can't find symbol in module
    wine: Unhandled page fault on write access to 0x00000000 at address 0x6a4e2a20 (thread 0061), starting debugger...
    Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x7b83cf72).
    Register dump:
     CS:0073 SS:007b DS:007b ES:007b FS:0033 GS:003b
     EIP:7b83cf72 ESP:0032ab84 EBP:0032abf8 EFLAGS:00000283(   - --  I S - - -C)
     EAX:7b827b5d EBX:7b8c2000 ECX:19930520 EDX:0032aba4
     ESI:00000003 EDI:0032b188
    Stack dump:
    0x0032ab84:  0032ac24 0000000c 7bc55d53 c0000005
    0x0032ab94:  00000000 00000000 6a4e2a20 00000002
    0x0032aba4:  00000001 00000000 6cdd6090 6cefec7c
    0x0032abb4:  7cf56694 00000020 00000000 029ed986
    0x0032abc4:  661c2fdf 00000020 7cfbe000 029ed986
    0x0032abd4:  02a10e60 00000000 00000000 01411da0
    Backtrace:
    =>0 0x7b83cf72 in kernel32 (+0x2cf72) (0x0032abf8)
      1 0x7e5796e6 _CxxThrowException+0x45() in msvcr71 (0x0032ac38)
      2 0x670d20cd in qtcore4 (+0xd20cc) (0x0032f790)
      3 0x670d5036 in qtcore4 (+0xd5035) (0x67057160)
    0x7b83cf72: movl        0xfffffff4(%ebp),%ecx
    Modules:
    Module  Address                 Debug info      Name (154 modules)
    PE        330000-  3f0000       Deferred        vooblynat3
    PE        400000-  42c000       Deferred        voobly
    PE        540000-  752000       Deferred        lobby
    PE        760000-  865000       Deferred        messenger
    PE        870000-  954000       Deferred        vooblynat1
    PE        960000-  9ec000       Deferred        launch
    PE        ba0000-  ba9000       Deferred        qgif4
    PE        bb0000-  bd0000       Deferred        qjpeg4
    PE       2440000- 264a000       Deferred        nss3
    PE      10000000-1009d000       Deferred        gui
    PE      53000000-5312a000       Deferred        anticheat1
    PE      64000000-6418d000       Deferred        qtnetwork4
    PE      65000000-65718000       Deferred        qtgui4
    PE      661c0000-662a2000       Deferred        mozglue
    PE      67000000-671ef000       Export          qtcore4
    PE      69e40000-6d0e9000       Deferred        xul
    ELF     7b800000-7ba6c000       Dwarf           kernel32<elf>
      \-PE  7b810000-7ba6c000       \               kernel32
    ELF     7bc00000-7bcfa000       Deferred        ntdll<elf>
      \-PE  7bc20000-7bcfa000       \               ntdll
    ELF     7bf00000-7bf04000       Deferred        <wine-loader>
    ELF     7c92c000-7c9fe000       Deferred        crypt32<elf>
      \-PE  7c940000-7c9fe000       \               crypt32
    ELF     7c9fe000-7ca34000       Deferred        wintrust<elf>
      \-PE  7ca00000-7ca34000       \               wintrust
    ELF     7ca34000-7ca7a000       Deferred        usp10<elf>
      \-PE  7ca40000-7ca7a000       \               usp10
    ELF     7ca7a000-7caec000       Deferred        setupapi<elf>
      \-PE  7ca80000-7caec000       \               setupapi
    ELF     7caec000-7cb20000       Deferred        secur32<elf>
      \-PE  7caf0000-7cb20000       \               secur32
    ELF     7ce04000-7ce19000       Deferred        rasdlg<elf>
      \-PE  7ce10000-7ce19000       \               rasdlg
    ELF     7ce19000-7ce36000       Deferred        libgcc_s.so.1
    ELF     7ce3d000-7ce59000       Deferred        rasapi32<elf>
      \-PE  7ce40000-7ce59000       \               rasapi32
    ELF     7ceb0000-7cee0000       Deferred        netapi32<elf>
      \-PE  7cec0000-7cee0000       \               netapi32
    ELF     7cee0000-7cef4000       Deferred        msimg32<elf>
      \-PE  7cef0000-7cef4000       \               msimg32
    ELF     7cef4000-7cf10000       Deferred        wsock32<elf>
      \-PE  7cf00000-7cf10000       \               wsock32
    ELF     7cf10000-7cfc8000       Deferred        msvcrt<elf>
      \-PE  7cf30000-7cfc8000       \               msvcrt
    ELF     7cfc8000-7d1aa000       Deferred        mshtml<elf>
      \-PE  7cfe0000-7d1aa000       \               mshtml
    ELF     7d1aa000-7d1d2000       Deferred        mpr<elf>
      \-PE  7d1b0000-7d1d2000       \               mpr
    ELF     7d1d2000-7d250000       Deferred        wininet<elf>
      \-PE  7d1e0000-7d250000       \               wininet
    ELF     7d250000-7d2f4000       Deferred        urlmon<elf>
      \-PE  7d260000-7d2f4000       \               urlmon
    ELF     7d2f4000-7d38e000       Deferred        ieframe<elf>
      \-PE  7d300000-7d38e000       \               ieframe
    ELF     7d38e000-7d3a7000       Deferred        userenv<elf>
      \-PE  7d390000-7d3a7000       \               userenv
    ELF     7d3a7000-7d3c6000       Deferred        wintab32<elf>
      \-PE  7d3b0000-7d3c6000       \               wintab32
    ELF     7d40c000-7d475000       Deferred        dbghelp<elf>
      \-PE  7d410000-7d475000       \               dbghelp
    ELF     7d475000-7d49f000       Deferred        iphlpapi<elf>
      \-PE  7d480000-7d49f000       \               iphlpapi
    ELF     7d49f000-7d4cf000       Deferred        p11-kit-trust.so
    ELF     7d5cf000-7d5d8000       Deferred        librt.so.1
    ELF     7d5d8000-7d5f0000       Deferred        libresolv.so.2
    ELF     7d655000-7d65c000       Deferred        libffi.so.6
    ELF     7d65c000-7d661000       Deferred        libgpg-error.so.0
    ELF     7d661000-7d665000       Deferred        libkeyutils.so.1
    ELF     7d665000-7d6b0000       Deferred        libdbus-1.so.3
    ELF     7d6b0000-7d6ec000       Deferred        libp11-kit.so.0
    ELF     7d6ec000-7d700000       Deferred        libtasn1.so.6
    ELF     7d700000-7d786000       Deferred        libgcrypt.so.11
    ELF     7d786000-7d792000       Deferred        libkrb5support.so.0
    ELF     7d792000-7d797000       Deferred        libcom_err.so.2
    ELF     7d797000-7d7c7000       Deferred        libk5crypto.so.3
    ELF     7d7c7000-7d885000       Deferred        libkrb5.so.3
    ELF     7d885000-7d94b000       Deferred        libgnutls.so.26
    ELF     7d94b000-7d991000       Deferred        libgssapi_krb5.so.2
    ELF     7d991000-7d9fe000       Deferred        libcups.so.2
    ELF     7da02000-7da09000       Deferred        libnss_dns.so.2
    ELF     7da09000-7da0d000       Deferred        libnss_mdns4_minimal.so.2
    ELF     7da0d000-7da21000       Deferred        psapi<elf>
      \-PE  7da10000-7da21000       \               psapi
    ELF     7da21000-7da5a000       Deferred        uxtheme<elf>
      \-PE  7da30000-7da5a000       \               uxtheme
    ELF     7da5a000-7da60000       Deferred        libxfixes.so.3
    ELF     7da60000-7da6b000       Deferred        libxcursor.so.1
    ELF     7da6c000-7da7e000       Deferred        libavahi-client.so.3
    ELF     7da7e000-7da8c000       Deferred        libavahi-common.so.3
    ELF     7dae6000-7db0f000       Deferred        libexpat.so.1
    ELF     7db0f000-7db4a000       Deferred        libfontconfig.so.1
    ELF     7db4a000-7db72000       Deferred        libpng12.so.0
    ELF     7db72000-7db8c000       Deferred        libz.so.1
    ELF     7db8c000-7dc2c000       Deferred        libfreetype.so.6
    ELF     7dc2c000-7dc3c000       Deferred        libxi.so.6
    ELF     7dc3c000-7dc40000       Deferred        libxcomposite.so.1
    ELF     7dc40000-7dc4b000       Deferred        libxrandr.so.2
    ELF     7dc4b000-7dc56000       Deferred        libxrender.so.1
    ELF     7dc56000-7dc5c000       Deferred        libxxf86vm.so.1
    ELF     7dc5c000-7dc60000       Deferred        libxinerama.so.1
    ELF     7dc60000-7dc82000       Deferred        libxcb.so.1
    ELF     7dc82000-7ddb6000       Deferred        libx11.so.6
    ELF     7ddb6000-7ddc9000       Deferred        libxext.so.6
    ELF     7ddc9000-7de5f000       Deferred        winex11<elf>
      \-PE  7ddd0000-7de5f000       \               winex11
    ELF     7de5f000-7df1a000       Deferred        winmm<elf>
      \-PE  7de70000-7df1a000       \               winmm
    ELF     7df1a000-7df5d000       Deferred        winspool<elf>
      \-PE  7df20000-7df5d000       \               winspool
    ELF     7df5d000-7e069000       Deferred        comctl32<elf>
      \-PE  7df60000-7e069000       \               comctl32
    ELF     7e069000-7e0e4000       Deferred        shlwapi<elf>
      \-PE  7e080000-7e0e4000       \               shlwapi
    ELF     7e0e4000-7e395000       Deferred        shell32<elf>
      \-PE  7e0f0000-7e395000       \               shell32
    ELF     7e395000-7e484000       Deferred        comdlg32<elf>
      \-PE  7e3a0000-7e484000       \               comdlg32
    ELF     7e484000-7e4c1000       Deferred        ws2_32<elf>
      \-PE  7e490000-7e4c1000       \               ws2_32
    ELF     7e4c1000-7e4e6000       Deferred        imm32<elf>
      \-PE  7e4d0000-7e4e6000       \               imm32
    ELF     7e4e6000-7e508000       Deferred        libtinfo.so.5
    ELF     7e508000-7e52d000       Deferred        libncurses.so.5
    ELF     7e550000-7e600000       Dwarf           msvcr71<elf>
      \-PE  7e570000-7e600000       \               msvcr71
    ELF     7e600000-7e743000       Deferred        msvcp71<elf>
      \-PE  7e640000-7e743000       \               msvcp71
    ELF     7e743000-7e886000       Deferred        oleaut32<elf>
      \-PE  7e760000-7e886000       \               oleaut32
    ELF     7e886000-7e90b000       Deferred        rpcrt4<elf>
      \-PE  7e890000-7e90b000       \               rpcrt4
    ELF     7e90b000-7ea52000       Deferred        ole32<elf>
      \-PE  7e920000-7ea52000       \               ole32
    ELF     7ea52000-7eacc000       Deferred        advapi32<elf>
      \-PE  7ea60000-7eacc000       \               advapi32
    ELF     7eacc000-7ebed000       Deferred        gdi32<elf>
      \-PE  7eae0000-7ebed000       \               gdi32
    ELF     7ebed000-7ed65000       Deferred        user32<elf>
      \-PE  7ec00000-7ed65000       \               user32
    ELF     7ef65000-7ef72000       Deferred        libnss_files.so.2
    ELF     7ef72000-7ef7e000       Deferred        libnss_nis.so.2
    ELF     7ef7e000-7ef97000       Deferred        libnsl.so.1
    ELF     7ef97000-7efdd000       Deferred        libm.so.6
    ELF     7efdf000-7efe6000       Deferred        libxdmcp.so.6
    ELF     7efe6000-7f000000       Deferred        version<elf>
      \-PE  7eff0000-7f000000       \               version
    ELF     b7322000-b7326000       Deferred        libxau.so.6
    ELF     b7326000-b732f000       Deferred        libnss_compat.so.2
    ELF     b7330000-b7335000       Deferred        libdl.so.2
    ELF     b7335000-b74e3000       Deferred        libc.so.6
    ELF     b74e4000-b7500000       Deferred        libpthread.so.0
    ELF     b7523000-b76e9000       Dwarf           libwine.so.1
    ELF     b76eb000-b770d000       Deferred        ld-linux.so.2
    ELF     b770d000-b770e000       Deferred        [vdso].so
    Threads:
    process  tid      prio (all id:s are in hex)
    0000000e services.exe
            0000001e    0
            0000001d    0
            00000014    0
            00000010    0
            0000000f    0
    00000012 winedevice.exe
            0000001c    0
            00000019    0
            00000018    0
            00000013    0
    0000001a plugplay.exe
            00000020    0
            0000001f    0
            0000001b    0
    0000002c rpcss.exe
            0000006e    0
            0000006d    0
            00000032    0
            00000031    0
            00000030    0
            0000002e    0
            0000002d    0
    00000060 (D) C:\Program Files\Voobly\voobly.exe
            0000007a    0
            00000079    0
            00000078    0
            00000077    0
            00000076    0
            00000075    0
            00000074    0
            00000073    0
            00000072    0
            00000071    0
            0000006b    0
            0000006a    0
            00000069    0
            00000068    0
            00000067    0
            00000061    0 <==
    00000062 explorer.exe
            00000066    0
            00000065    0
            00000064    0
            00000063    0
    System information:
        Wine build: wine-1.8-rc4 (Staging)
        Platform: i386
        Version: Windows 5.1 (0)
        Host system: Linux
        Host version: 3.13.0-37-generic

**Comment by slackner** [comment]
Sorry, but it seems like your bug report remained unnoticed because this bug tracker is no longer used. If you can still reproduce the problem, please open a new bug report at https://bugs.winehq.org/enter_bug.cgi?product=Wine, including the terminal output as attachment, and an explanation how the issue can be reproduced. Please note that changing the Windows version reported by Wine is not recommended, and can cause all kind of side-effects, so try to switch it back to the default settings (Win XP).

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
