### ISSUE TITLE
Add Perflib registry keys

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#35]
RFC for "Add Perflib registry keys"

|  |  | 
| ------------- | ------------- |
| **Bug**       | https://bugs.winehq.org/show_bug.cgi?id=33661 |
| **Patch**       | https://bugs.winehq.org/attachment.cgi?id=48889 |

The patch is pretty straight forward and should solve the issue. The only problem left is that the registry key also contains a locale depended subkey filled with translations. The patch only adds the english translation.

**Comment by slackner** [comment]
The patch was already added, closing.
