### ISSUE TITLE
Add support for job objects

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#40]
RFC for "Add support for job objects"

|  |  | 
| ------------- | ------------- |
| **Bug**       | http://bugs.winehq.org/show_bug.cgi?id=33723 |
| **Patch** | http://bugs.winehq.org/attachment.cgi?id=48637&action=diff |

The number of tests seems to be very small, I don't think they test really everything.

**Comment by compholio** [comment]
An OSS application that uses this is "pip" for Python:
http://qt-project.org/wiki/PySide_Binaries_Windows
However, it also wants NtQueryInformationJobObject.

**Comment by compholio** [comment]
Rebased patch:
https://gist.github.com/compholio/8dd4bbcc4228fd57b445

Horrible hack for "pip":
https://gist.github.com/compholio/11777023e0f88ee73a06

**Comment by slackner** [comment]
Well, the main problem why I haven't added this patchset yet is because it is most probably not completely correct. The tests are very limited and the implementation doesn't seem to match the comments on MSDN. As the stubs are sufficient for most other applications, we have to be very careful when replacing them with a real implementation.

**Comment by compholio** [comment]
Agreed, I just figured while I was playing with pip that I'd make a quick update.  I think we can put something together that's a lot better though, besides needing splitting this patch has some clear issues that need to be resolved before we can integrate it.

**Comment by slackner** [comment]
Marking as milestone for 1.7.35. I am not sure if this is realistic, but as a lot of users ask about it, we should probably give it a higher priority. ;)

**Comment by slackner** [comment]
I fear that we'll have not enough time to include this patch already in 1.7.35. We probably might be able to get at least a couple of tests included, but the main implementation still needs a lot of changes. I'll remove the milestone target.

**Comment by deri82** [comment]
League of legends has NtIsProcessInJob calls...Just tried the game today.

**Comment by titan73** [comment]
A bug for job objects has been entered in new tracker at https://bugs.wine-staging.com/show_bug.cgi?id=134. This github issue can be closed now.

**Comment by slackner** [comment]
Closing.
