### ISSUE TITLE
Add support for ID3DXFont::DrawTextA/W

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#41]
RFC for "Add support for ID3DXFont::DrawTextA/W"

|  |  | 
| ------------- | ------------- |
| **Bug**       | http://bugs.winehq.org/show_bug.cgi?id=24754 |
| **Patch** | http://repo.or.cz/w/wine/d3dx9TW.git/commitdiff/4e4e47bf0ba3236713472dfe502739ffc4a0e686 |

Needs to be rebased and cleaned up.

**Comment by titan73** [comment]
The patch http://ix.io/fBa fixes the remaining issues in Air Strike and should fix the misplaced text in Stronghold Kingdoms.

**Comment by titan73** [comment]
Stronghold kingdoms issue reported fixed https://bugs.winehq.org/show_bug.cgi?id=24754#c23.

**Comment by slackner** [comment]
Since the font issue is resolved with your updated patch this issue can be closed. Good job!
