### ISSUE TITLE
Escape path in ShellExecuteEx

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#46]
RFC for "Escape Path in ShellExecuteEx"

|  |  | 
| ------------- | ------------- |
| **Bug**       | https://bugs.winehq.org/show_bug.cgi?id=19666 |

No patch yet, but there are already some suggestions in the bug tracker.

**Comment by compholio** [comment]
Since I was already in the area, I rebased the patch for this:
http://pastebin.com/raw.php?i=2bwqjzsZ

**Comment by titan73** [comment]
Is there something incorrect in this patch? Tests are provided. Why not add it to wine-staging?

**Comment by compholio** [comment]
I was going to see what it does with an already-quoted string first.  My plan was to do this yesterday, but I screwed up the CSMT rebase and had to do it twice :/

**Comment by compholio** [comment]
Moved to the new bug tracker: https://bugs.wine-staging.com/show_bug.cgi?id=14
