### ISSUE TITLE
Improvement of "ws2_32-TransmitFile: ws2_32: Check for invalid parameters in TransmitFile." (and following)

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#61]
Missing check for the return value of get_sock_fd:
```
+    fd = get_sock_fd( s, 0, NULL );
```

Besides that, in the following patch, I still think its necessary to check the number of bytes transmitted, instead of hoping that it will always succeed. I'm pretty sure I mentioned that already some time ago, but probably there was a good reason, and I just forgot it.
```
+            if (WS_send( s, buffer, n, 0 ) == SOCKET_ERROR)
+                goto cleanup;
+            bytes_sent += n;
```

For the async-support: I think it doesn't make much sense to implement it that way, async only makes sense when you add support for partial sending the file. This required to keep track of which headers/footers have already been sent. I also think your async function has the wrong number of arguments (only 3 instead of 4)?

**Comment by compholio** [comment]
Fixed by commit 150c6dce287f71afea5e6825dc5906548c9c6c0d.
