### ISSUE TITLE
Separate patch status / sign-off / comments page.

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#67]
We already have a huge amount of patches in our repo (159 at the moment). Some patches could easily be improved, but its useless to open a separate bug report for each one. Missing checks when calling HeapAlloc, missing cleanup in some error paths, ...

I have no problem with reviewing (and fixing) those patches, but its really difficult to keep track of what was already reviewed, and where additional changes are required. We most probably don't want a patch review queue like Wine - but something similar would be useful.

I would suggest to have a separate page, where the status of all our patchsets is tracked. For each patchset it should be possible to add reviews, which are automatically "invalidated" when the patch is updated. If its not too difficult I would even suggest to add the possibility to add code remarks. All this information is in a separate database, and not directly in our git repository.

We (and other people that want to review patches) could take a look at the code, and then give it a rating, add comments, add their "sign-off" if its good enough for upstream Wine, and so on. We can still use the bug tracker for critical issues and new patches which should be included of course, this is just an addition.

The main idea is to have an overview page, where its easy visible which patches haven't been reviewed by multiple people yet and for which patches improvements are possible. My (final) goal is to have each patchset be reviewed/discussed and signed-off by multiple persons, to ensure a similar high quality as upstream wine. This should also help to make the whole Wine-Compholio idea look much more professional.

**Comment by slackner** [comment]
I recently discussed again with @compholio about this idea, and he was planning to take a closer look. One of the ideas was to integrate the service somehow into github. Erich was planning to take a look during the boring plane flights ;)

**Comment by titan73** [comment]
He nice! :)

**Comment by slackner** [comment]
Closing. I fear we might have to use the "Patch submission" category in our new bugtracker, unless someone feels motivated enough to implement a separate patch submission status website. ;)
